### ISSUE TITLE
VariableTypeDetector is not working properly

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#1028]
The VariableTypeDetector causes runConfAvailableTest.sh to fail sometimes. The problem is that /model/RandomTime/Random is stopped being tracked:

```
"Stopped tracking the variable of event type 8(/model/RandomTime/Random) with Path:
/model/RandomTime
because of irregular variable types."
```

Following Warning is shown always when the error is encountered:
```
/etc/aminer/conf-enabled/scipy/stats/_discrete_distns.py:67: RuntimeWarning: divide by zero encountered in _binom_pdf
  return _boost._binom_pdf(x, n, p)
```

Using `var_reduction_thres: 0` the error is mitigated. However detecting the type of "Random: " (FixedDataModelElement) and an integer number (DecimalIntegerValueModelElement) should be easily possible.

**Comment by hoeldg** [comment]
VTD works as intended
