### ISSUE TITLE
CI-Pipeline fails

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#1052]
The Tests for try-it-out seem to fail

**Comment by dITySoftware** [comment]
Have you updated the wiki files I have sent per mail?

**Comment by whotwagner** [comment]
It also fails with the updated files

**Comment by dITySoftware** [comment]
I can't really fix the issue with integration test 2. But when I ran it as the only process, it never failed. Now the tests are green.

**Comment by whotwagner** [comment]
We do things paralell now. maybe there is nothing wrong with the tryit-out tests, but with the getting started tests. you might try to disable the getting-started tests and see if the tryit-out fail again.

**Comment by dITySoftware** [comment]
Ah, sorry I forgot to write that you need to accept the open PR #1050. There are the adapted tests and needed changes, that allow parallel execution.

**Comment by dITySoftware** [comment]
This issue is fixed.
