### ISSUE TITLE
AminerRemoteControl: Whitelist specific path

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#106]
A scenario is that when running the AMiner in detection mode, one new anomaly occurs over and over, because something in the system has changed (e.g., ip). The operator confirms that this is a valid change and commands the AMiner to relearn this one specific value (add to persistency or override previous value).

**Comment by dITySoftware** [comment]
Should the NewMatchPathValueDetector also support whitelisting? The whitelist_event method is not implemented.

**Comment by dITySoftware** [comment]
I think this was already possible before. I have added an example to the AMinerRemoteControl demo. An error occured in AMinerRemoteControl. I fixed in PR #193.

**Comment by dITySoftware** [comment]
Please move this issue to Done.
