### ISSUE TITLE
Extend yaml config to support more detectors

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#107]
Either add code for new detectors manually, or - if possible - allow to add any detectors with 1:1 mapping of keys and values to parameters.

**Comment by dITySoftware** [comment]
The tuple_transformation_function of the EnhancedNewMatchPathValueComboDetector is problematic. How should a python function be defined in the yaml config?

**Comment by dITySoftware** [comment]
HistogramAnalysis is also problematic. How should a list of tuples of paths and BinDefinitions be defined in the schema?

**Comment by landauermax** [comment]
I am not sure if it is possible to define functions in yaml. If it is not reasonably possible, we can state that this detector is only supported with python configs.

I think tupels of paths can be defined as lists like it was done in the Combo Detector. For BinDefinitions, i guess it is necessary to define it as a new object and use an ID as a parameter in the detector, similar to the parsing model elements.

**Comment by dITySoftware** [comment]
how about defining the function as a multiline string?

**Comment by landauermax** [comment]
It would probably be possible, but I would prefer to not do it that way. We have the yaml config specifically to move away from python code. I think a user-friendly option would be to have some pre-defined functions ready that are then selected by setting a parameter with a simple strings that selects the specific function.

**Comment by dITySoftware** [comment]
That's a good idea. Can you think of any useful default function. For example the AMiner Demo needs a function that sets every x-th value the auto_include_flag to False. This is needed for the Detector to produce an output.

I will implement this with a dictionary. Later on other functions can be added.

**Comment by landauermax** [comment]
I assume that we will have use-cases at some point that will require specific functions, which we can add later. I could imagine that it would be useful to have a function that rounds float values to the nearest integer, which are then used for combo detection (to avoid that floats with many digits create extremely many possible combinations). Alternatively, we could have a function with some string operations, e.g., only consider the first x characters of a token.

**Comment by dITySoftware** [comment]
Should the MatchPathFilter and MatchValueFilter of the AtomFilters class be implemented?

**Comment by dITySoftware** [comment]
Why is the NewMatchPathDetector always automatically added without being in the configs?

**Comment by landauermax** [comment]
Yes, MatchPathFilter and MatchValueFilter are required. They are used just as normal analysis components.

We thought that the NewMatchPathDetector is anyway always used, so we automatically added it to make the config smaller. Even if you have no analysis components in the pipeline, the AMiner requires at least the UnparsedAtomHandler and the NewMatchPathDetector to work properly.

**Comment by dITySoftware** [comment]
> Yes, MatchPathFilter and MatchValueFilter are required. They are used just as normal analysis components.
> 
> We thought that the NewMatchPathDetector is anyway always used, so we automatically added it to make the config smaller. Even if you have no analysis components in the pipeline, the AMiner requires at least the UnparsedAtomHandler and the NewMatchPathDetector to work properly.

Added those Filters.

This issue is fixed in PR #165 and can be closed after review.
