### ISSUE TITLE
Discussion: Extend available installation systems in ansible and document manual changes in the install script. 

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/logdata-anomaly-miner#1080]
The manual steps to install aminer should be better documented.

Are there other possible measures to check whether aminer could be running on the system? 

I would suggest to add further checks and normally install the aminer if possible, but add a warning before installation like this:
WARNING: This system is not fully supported by the aminer. Supported Systems are <...>. Do you want to continue the installation process? [y/n]

As there is a specific installation process for different ubuntu/debian version, the checks should be extended to the necessary variables. I guess this has to do with the pre-installed python version.

This could also help with reducing necessary steps to add a newer Debian or Ubuntu versions.

**Comment by whotwagner** [comment]
Yeah, I will create checks if the linux distribution is supported or not

**Comment by ernstleierzopf** [comment]
I would suggest to create tests for CentOS and Fedora, because these are own system and not Debian/Ubuntu based.

We also might try to support some type of Arch distribution like Gentoo, but if you are using an Arch distribution you probably know what you are doing and don't need these tests and as of my understanding you install Arch to tweak the system perfectly for your needs.

As CentOS no longer provides docker images, I would suggest RHEL 9: https://hub.docker.com/r/redhat/ubi9
https://hub.docker.com/_/fedora

What do you think about these suggestions?
