### ISSUE TITLE
yaml-config: semantic checks

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#109]
Add semantic checks for the yaml config so that config errors can be displayed properly

**Comment by skopikf** [comment]
MissingMatchPathValueDetector: required={type, path (but *not* paths)}, optional={check_interval, realert_interval}

**Comment by dITySoftware** [comment]
> MissingMatchPathValueDetector: required={type, path (but _not_ paths)}, optional={check_interval, realert_interval}

changed in PR #160

**Comment by dITySoftware** [comment]
There is no way to check if the config contains parameters, which are for example not used by the analysis component as default values are set. However the schema checks if the parameters are existing in any of the components.

**Comment by dITySoftware** [comment]
Is this issue solved or is something missing?

**Comment by whotwagner** [comment]
Some things are missing, but I think I will split them in to multiple smaller issues
