### ISSUE TITLE
Improve error handling for incorrect timestamp paths

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1095]
It is very easy to forget to set the timestamp_paths in the Input section of the config.yml. The result is that some detectors that rely on timing information raise errors, e.g. consider the following config/input/output:

```
LearnMode: True
AminerUser: 'aminer'
AminerGroup: 'aminer'

LogResourceList:
        - 'file:///home/ubuntu/file.log'

Parser:
        - id: syslogModel
          type: SyslogParsingModel
          name: 'syslog'
          args: 'syslog'

        - id: model
          start: True
          type: SequenceModelElement
          name: 'parser'
          args:
             - syslogModel

Input:
        multi_source: False
        timestamp_paths:
          - '/parser/incorrect_path/time'

Analysis:
        - type: 'EventFrequencyDetector'
          window_size: 10
          confidence_factor: 0.01
          num_windows: 2

EventHandlers:
        - id: "stpe"
          json: true
          type: "StreamPrinterEventHandler"
```

```
Mar  1 00:20:34 mail-1 dovecot: imap-login: Login: user=<clay>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=10299, secured, session=<IAEGCsCf5tJ/AAAB>
Mar  1 00:20:34 mail-1 dovecot: imap-login: Login: user=<clay>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=10299, secured, session=<IAEGCsCf5tJ/AAAB>
```

```
Traceback (most recent call last):
  File "/usr/bin/aminer", line 755, in <module>
    main()
  File "/usr/bin/aminer", line 480, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 89, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 336, in run_analysis
    handle_result = fd_handler_object.handle_stream()
  File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 325, in handle_stream
    self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 164, in consume_data
    if self.dispatch_atom(log_atom):
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 184, in dispatch_atom
    if handler.receive_atom(log_atom):
  File "/usr/lib/logdata-anomaly-miner/aminer/analysis/AtomFilters.py", line 52, in receive_atom
    handler_result = handler.receive_atom(log_atom)
  File "/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py", line 152, in receive_atom
    elif log_atom.atom_time >= self.next_check_time:
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
```

For someone who is not familiar with the AMiner, it is not obvious what the problem is and how it needs to be resolved. I think some detectors currently use the current real time in case that the log_atom.atom_time is None, but I would argue that this is also not optimal, since it may also cause problems (in particular, users who think that the detector operates on the timestamps from the logs, but in fact the detector uses the real time and thus produces incorrect results). I therefore suggest to review and change all detectors (except for those where obviously real time is required, such as the ParserCount) so that they only use the timestamp from the logs themselves; and that we maybe add a new parameter (use_real_time) that needs to be explicitly set to True in order to use the current real time instead of the time derived from the logs, i.e., when this is set the real time will overwrite the log_atom.atom_time.

**Comment by ernstleierzopf** [comment]
After thinking about the problem I decided it would be better to create the UseRealTime parameter as a global setting, because I can not think of use cases where only one parser should use real time and the others not.

**Comment by landauermax** [comment]
Yes, I think a global parameter is fine for this issue.
