### ISSUE TITLE
JSONParser: Different atom values when parsing boolean values

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#1096]
The VariableByteDataModelElement (with the alphabet as argument) and FixedWordlistDataModelElement (with string 'true') can both be used to parse the following line:
```
{"a": true}
```
but result in following atom values:
```
"/model/a_list": "1"
"/model/a_var": "true"
```
Please fix it by assigning the atom value "true".

**Comment by ernstleierzopf** [comment]
This is expected behavior as the result of the FixedWordlistDataModelElement is the index of the found word. If you think the FixedWordlistDataModelElement  should use the value itself, please discuss this in the group and open a new issue regarding the FixedWordlistDataModelElement .
