### ISSUE TITLE
Try It Out Run AMiner issue

### ISSUE THREAD

**Issue by marsup13** [ait-aecid/logdata-anomaly-miner#1121]
Hello I followed the instructions in Try It Out of the book Smart Log Data Analytics and the online version using this link: https://github.com/ait-aecid/logdata-anomaly-miner/wiki/aminer-TryItOut#configuration-of-the-aminer-for-ait-ldsv11 

Unfortunately, I had errors when running aminer command. I tried using the -C option but I had the same problem

This is the output of the terminal (I am using ubuntu 18.04.6 on a virtual machine)
(base) marwane@ubuntu:/etc/aminer/conf-available/ait-lds$ sudo aminer -C --config /etc/aminer/config.yml
Traceback (most recent call last):
  File "/usr/bin/aminer", line 755, in <module>
    main()
  File "/usr/bin/aminer", line 480, in [main]
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 89, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 255, in run_analysis
    self.analysis_context.build_analysis_pipeline()
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 172, in build_analysis_pipeline
    self.aminer_config.build_analysis_pipeline(self)
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 130, in build_analysis_pipeline
    parsing_model = build_parsing_model()
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 234, in build_parsing_model
    raise TypeError(msg)
TypeError: "args" has to be a list when using the FirstMatchModelElement. Currently args is defined as b'apacheAccessModel'
sys:1: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
aminer: Analysis child process 22259 terminated unexpectedly with signal 0x100

Attached you find my config.yml file:

[config.txt](https://github.com/ait-aecid/logdata-anomaly-miner/files/8848804/config.txt)

Please let me know if you could help me resolve this issue.
Thanks in advance!

**Comment by landauermax** [comment]
Hi! I ran your config.yml and was able to reproduce the problem. To resolve it, you have to specify the args of the FirstMatchModelElement as a list, which is currently defined as a simple value (`args: apacheAccessModel`) in your config.yml. So the whole parsing component should look like this (only the last two lines changed):

```yml
Parser:
     - id: 'apacheAccessModel'
       type: ApacheAccessParsingModel
       name: 'apacheAccess'
       args: 'apacheAccess'

     - id: 'START'
       start: True
       type: FirstMatchModelElement
       name: 'parser'
       args:
        - apacheAccessModel
```

With these changes in the config, I could run the aminer successfully. Could you also please confirm that you are using the current version of the aminer? It should be 2.5.1:

```
max@max-VirtualBox:~/test$ aminer -v
   (Austrian Institute of Technology)
       (https://aecid.ait.ac.at)
            Version: 2.5.1 
```

The code in the book was created for aminer version 2.2.3, which had different constraints in the config.yml; I assume that this is the source of your problem. If you stick to the code that we provide in the online version of the try-it-out, you should not have any problems running the aminer. Let me know if this fixed your problem and feel free to contact us again if any other issues appear.

**Comment by marsup13** [comment]
Hello @landauermax , thanks for your prompt reply. 
Yes, it is working now.
As for my version of AMiner:
 (Austrian Institute of Technology)
       (https://aecid.ait.ac.at)
            Version: 2.5.1     

Have a great day/evening!
