### ISSUE TITLE
Travis does not exit with errors

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#114]
Failed unit-tests do not exit with errors

![image](https://user-images.githubusercontent.com/15659571/87804789-a9cfd700-c854-11ea-8e2f-bed34670b169.png)

**Comment by whotwagner** [comment]
I believe that this happens because the unittests do not run directly in travis but in the runUnittests.sh. Since travis never sees the return-code of the unit-tests, the tests will always be SUCESSFUL in travis

**Comment by dITySoftware** [comment]
Fixed in PR #124 . This issue can be closed.

**Comment by landauermax** [comment]
@whotwagner please review.

**Comment by whotwagner** [comment]
Looks good.
