### ISSUE TITLE
contradicting interval settings in MissingMatchPathValueDetector 

### ISSUE THREAD

**Issue by skopikf** [ait-aecid/logdata-anomaly-miner#117]
The persistency of the MissingMatchPathValueDetector stores the maximum allowed gap between observations (=interval); the same parameter can be configured in the config.yml. If the interval is changed in the config, but an interval has been persisted along with a token to look for, the changed config has no effect and the persistency takes precedence. Effectively, the intervals for once persisted tokens cannot be changed any more via the config.
Possible Fix: The interval should not be persisted, but instead loaded each time from the config -- side effects?

**Comment by skopikf** [comment]
even worse: the persistency just keeps the expected value, but not the affected path. If the path is changed in the config, and the aminer restarted, the detector tries to match the "old" values in the persistency to the new path in th config

**Comment by dITySoftware** [comment]
I can try to solve this issue. Please assign it to me.

**Comment by dITySoftware** [comment]
> The persistency of the MissingMatchPathValueDetector stores the maximum allowed gap between observations (=interval); the same parameter can be configured in the config.yml. If the interval is changed in the config, but an interval has been persisted along with a token to look for, the changed config has no effect and the persistency takes precedence. Effectively, the intervals for once persisted tokens cannot be changed any more via the config.
> Possible Fix: The interval should not be persisted, but instead loaded each time from the config -- side effects?

I have changed the implementation that the interval is reset after loading (value[1]) and the next check time to value[0] + default_interval. I don't think there are severe side effects. The values are also only changed, when the default_interval changes!

All values, which paths were changed, are now deleted at loading time.
