### ISSUE TITLE
Incorrect test case evaluations

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#119]
The test case evaluation of test#5 of the MissingMatchPathValueDetector is incorrect: https://github.com/ait-aecid/logdata-anomaly-miner/blob/master/aecid-testsuite/unit/analysis/MissingMatchPathValueDetectorTest.py#L124 

The test case should evaluate whether (a==b) or (a==c), but is in fact evaluating (a==b) or (c), which means that the test never fails as long as c is some value that evaluates to True. All existing tests have to be checked for similar bugs.

Also, as outlined in the Python docs, assertTrue should be avoided when more specific test methods are available, such as assertEqual. This could have helped to find the issue earlier and should be applied for all existing and future tests.

**Comment by dITySoftware** [comment]
fixed in PR #120
