### ISSUE TITLE
TryItout-Check fails

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#1197]
During the creation of the new release 2.6.0 the tryitout-check for the main-branch fail. I believe this happens because the wiki-branches(dev/master) are different. I believe that  we forgot to merge from master to development after the last release and that we have changes in the master that are missing in developent. I don't want to mix things up, so I prefer if @ernstleierzopf will fix this issue.

**Comment by ernstleierzopf** [comment]
**git diff development master** shows that only new text was added to the master branch. Could you please merge all of the changes from master into the development branch of the wiki? @whotwagner @landauermax

**Comment by whotwagner** [comment]
done

**Comment by ernstleierzopf** [comment]
Also I will create two separate pull requests for the main branch and for the development branch.

**Comment by whotwagner** [comment]
> Also I will create two separate pull requests for the main branch and for the development branch.

No, that is not necessarry. Just create one pullrequest with very few commit's. I'll cherry-pick those commits into the main
