### ISSUE TITLE
The accuracy and trustworthiness of AECID and AMiner classification

### ISSUE THREAD

**Issue by marsup13** [ait-aecid/logdata-anomaly-miner#1198]
Hello guys,

I was wondering please what are the indicators and parameters that prove and control the accuracy and trustworthiness of AECID and AMiner classification/clustering of anomalies and normal behavior based on the logs?

Thanks in advance!

**Comment by 4cti0nfi9ure** [comment]
Hi,

it is hard to answer this question in general for all AECID components and AMiner detectors. I suggest to go through our scientific publications that include evaluation results and discuss parameter selection with respect to accuracy and other metrics. Both the readme of the AMiner (https://github.com/ait-aecid/logdata-anomaly-miner#readme) and the AECID website (https://aecid.ait.ac.at/further-information/) include links to several of our publications.

One of the following works might be of interest for you:

- AMiner overview: https://dl.acm.org/doi/abs/10.1145/3567675
- AECID-PG: https://ieeexplore.ieee.org/abstract/document/8717887
- Incremental Clustering: https://dl.acm.org/doi/abs/10.1145/3098954.3098973
- Character-based Template Generator: https://dl.acm.org/doi/abs/10.1145/3320269.3384722
- Variable Correlation Detector (VCD): https://www.researchgate.net/profile/Florian-Skopik/publication/354944227_Iterative_Selection_of_Categorical_Variables_for_Log_Data_Anomaly_Detection/links/616ee699c891c4663aa2c2d1/Iterative-Selection-of-Categorical-Variables-for-Log-Data-Anomaly-Detection.pdf
