### ISSUE TITLE
Stop_learning_time only uses real time

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1230]
It seems that stop_learning_time and stop_learning_no_anomaly_time rely only on real time and cannot be used for forensic data set processing as described in the original issue: https://github.com/ait-aecid/logdata-anomaly-miner/issues/831

Also, it seems that only the functionality where the learning mode switches after no more anomalies have been observed for some time is implemented. What is missing is a functionality that switches the learn mode after a certain amount of time no matter when anomalies occurred.

**Comment by ernstleierzopf** [comment]
I have already addressed this issue in the rework of unittests in PR #1221 .
