### ISSUE TITLE
Log source path in anomalies output

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1231]
We need to add the name of the log source in the anomaly output (or multiple log sources if anomaly is based on multiple lines from different sources). We could name the field `LogResources` fitting to the config.yml. For example as in the last line of the following anomaly:

```
{
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 6,
    "AnalysisComponentType": "EntropyDetector",
    "AnalysisComponentName": "entropy_request",
    "Message": "Value entropy anomaly detected",
    "PersistenceFileName": "entropy_request",
    "TrainingMode": false,
    "AffectedLogAtomPaths": [
      "/model/fm/request/request"
    ],
    "AffectedLogAtomValues": [
      "/wp-content/uploads/2022/01/ekmkimzkps-1642996700.9285.php?wp_meta=WyIuL3dwaGFzaGNyYWNrLTAuMS93cGhhc2hjcmFjay5zaCIsICItdyIsICIkUFdEL3JvY2t5b3UudHh0IiwgIi1qIiwgIi4vd3BoYXNoY3JhY2stMC4xL2pvaG4tMS43LjYtanVtYm8tMTItTGludXg2NC9ydW4iLCAiLXUiLCAiamhhbGwiXQ%3D%3D"
    ],
    "CriticalValue": 0.03219069940839161,
    "ProbabilityThreshold": 0.05
  },
  "LogData": {
    "RawLogData": [
      "172.19.131.174 - - [24/Jan/2022:03:59:48 +0000] \"GET /wp-content/uploads/2022/01/ekmkimzkps-1642996700.9285.php?wp_meta=WyIuL3dwaGFzaGNyYWNrLTAuMS93cGhhc2hjcmFjay5zaCIsICItdyIsICIkUFdEL3JvY2t5b3UudHh0IiwgIi1qIiwgIi4vd3BoYXNoY3JhY2stMC4xL2pvaG4tMS43LjYtanVtYm8tMTItTGludXg2NC9ydW4iLCAiLXUiLCAiamhhbGwiXQ%3D%3D HTTP/1.1\" 200 506902 \"-\" \"python-requests/2.27.1\""
    ],
    "Timestamps": [
      1642996788
    ],
    "DetectionTimestamp": 1687185061,
    "LogLinesCount": 1,
    "LogResources": [
      "/var/log/apache2/access.log"
    ]
  }
}
```

**Comment by landauermax** [comment]
I suggest to add and store `resource` as a parameter in the ByteStreamLineAtomizer and pass the `log_resource` by the SimpleByteStreamLineAtomizerFactory. Since the LogAtom has access to the `source` (the atomizer), it can then also access the `resource` stored in the `source`. This way, the EventHandlers can simply add the `source` in the output.

**Comment by ernstleierzopf** [comment]
As log atoms are single lines of a single file, and the analysis is dependent on the state of the analysis component, it is not easily possible to determine all of the log resources which affect the anomaly.
To achieve the desired result, every single analysis component would have to track the last sources in an own set, which is hard to implement (when should these sources be removed in different analysis components like the PCA detector?).

An safer approach would be to use only the resource of the last log atom. Therefore I would not use a list of resources, but only a single string instead.
If that is not good enough, we can always improve on the implementation later on.

**Comment by ernstleierzopf** [comment]
example output of the aminer demo with the jsonConverterHandler-demo-config.py:
```
{
  "RuleInfo": {
    "Rule": "('/model/ECD/l',)<-('/model/ECD/h',)",
    "Expected": "500/500",
    "Observed": "80/81"
  },
  "LogData": {
    "RawLogData": [
      "h"
    ],
    "Timestamps": [
      1689519613.59
    ],
    "DetectionTimestamp": 1689519613.59,
    "LogLinesCount": 1,
    "AnnotatedMatchElement": {
      "/model/ECD/h": "h"
    }
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 9,
    "AnalysisComponentType": "EventCorrelationDetector",
    "AnalysisComponentName": "EventCorrelationDetector",
    "Message": "Correlation rule violated! Event b'l' is missing, but should precede event b'h'",
    "PersistenceFileName": "Default",
    "TrainingMode": true,
    "LogResource": "file:///tmp/syslog"
  }
}
```

**Comment by landauermax** [comment]
Analysis components anyway have to keep track of the log lines that are related to an anomaly. That is why they print out the RawLogData as a list; this list should contain all relevant log events (or a reasonable subset e.g. if they are too many).

Anyway, it is the task of someone implementing the analysis component to make that decision which log lines are relevant and how they are stored to add them to the list of RawLogData. These log lines can be from different log sources and thus the LogResource parameter needs to be a list that contains all sources that the log lines from the RawLogData originate from. Each analysis component already keeps track of the log lines that are desired to be printed - if you follow my suggestion and add the resource to the LogAtom, it should therefore not be difficult to print out the sources of all log lines that are contained in LogData.

**Comment by ernstleierzopf** [comment]
I agree, this is a desirable information for some analysis components, but at the moment this is not implemented. At the moment RawLogData is only set in the JsonConverterEventHandler and it contains only the last log atom (even though it is a list).
Most or all of the analysis components do not track the log_atoms, but instead the data or some abstraction of it.

If this is what's needed, I will go through all of the analysis components and implement that behavior.

**Comment by landauermax** [comment]
Okay. I do not see any disadvantage of tracking the log atoms instead of only the raw event data, so I would follow this approach. But this does not mean that all analysis components need to track all the log atoms, for example, the FrequencyDetector unually involves anomalies with many thousands of log atoms; obviously these should not be printed out and do not need to be stored, a single representative line as it is currently implemented is sufficient. Same for all other detectors.
