### ISSUE TITLE
Constraint or ignore specific log sources

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1236]
The AMiner currently has constraint or ignore lists for specific detectors that focus on paths. The same functionality should be provided for specific log sources. The reason for this is that even though two different log sources can be processed by the same parser, it may be necessary to analyze them in different ways (e.g. value detection on log source A and frequency detection on log source B) or just separately (e.g., both lines are analyzed for values detection but the trained models containing the observed values should be independent from each other, so that a new value can still be detected in one log source even though it was already observed in the other log source).

**Comment by ernstleierzopf** [comment]
This functionality has already been implemented with the granular LogResourceList in #1155 and #1225 .

**Comment by landauermax** [comment]
Please provide an example how this is done. As far as I know there are no parameters in the analysis components to constraint or ignore specific log resources.

**Comment by ernstleierzopf** [comment]
Well after reading the 5th time over this issue, I finally understand what needs to be done :D
This issue needs to be worked after implementing #1231 .
