### ISSUE TITLE
Create Testcases for Debian Bookworm

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#1238]
Debian Bookworm is out now. We need Testcases for the new Debian Release in our Pipeline

**Comment by ernstleierzopf** [comment]
Do we want to update the production dockerfile to bookworm at the same time we create these tests?

**Comment by whotwagner** [comment]
good point. yes, we want to update the production dockerfile. And we also want to drop support for very old ubuntu/debian releases

**Comment by ernstleierzopf** [comment]
what is very old? Ubuntu 18?
If yes, then forget the last Hotfix, because that only failes there.

**Comment by ernstleierzopf** [comment]
another candidate might be Debian Buster (release date 2019), but I would actually leave both of them in our test cases, because the time needed to be compatible with the older versions is actually very low.

**Comment by whotwagner** [comment]
> what is very old? Ubuntu 18? If yes, then forget the last Hotfix, because that only failes there.

I am going to discuss this first with @landauermax 
But I would like to drop support for ubuntu 18

**Comment by whotwagner** [comment]
It's settled. We are going to drop support for ubuntu 18. And we will add support for debian bookwyrm and ubuntu 22.04

**Comment by ernstleierzopf** [comment]
alright, closing the open PR then.

**Comment by ernstleierzopf** [comment]
should we also drop debian buster then? A nice rule of thumb would be to support the 2 latest versions of any supported OS.

**Comment by landauermax** [comment]
I had a talk with @whotwagner, we will maintain support for debian buster for now and @whotwagner will adapt the dockerfile accordingly.

**Comment by ernstleierzopf** [comment]
I am currently already building the debian bookworm to see if there are any dependencies missing, which need to be added in aminer-ansible. Will also do that for the Ubuntu 22.4 Image. @whotwagner is that ok for you?

**Comment by landauermax** [comment]
@whotwagner asked me to confirm that it is okay for him.
