### ISSUE TITLE
Unsupported locale settings and aminerDemo.sh

### ISSUE THREAD

**Issue by skopikf** [ait-aecid/logdata-anomaly-miner#128]
local execution of aminerDemo.sh on a(n almost) fresh Debian10 throws the following errors. Some problems with locale settings?!

debian@debian10:~/logdata-anomaly-miner/aecid-testsuite/demo/AMiner$ ./aminerDemo.sh 
Demo started..

WARNING: SECURITY: No secure open yet due to missing openat in python!
INFO: No privilege separation when started as unprivileged user
WARNING: SECURITY: Open should use O_PATH, but not yet available in python
WARNING: SECURITY: No secure open yet due to missing openat in python!
WARNING: SECURITY: No checking for backdoor access via POSIX ACLs, use "getfacl" from "acl" package to check manually.
Traceback (most recent call last):
  File "/usr/bin/AMiner", line 435, in <module>
    main()
  File "/usr/bin/AMiner", line 159, in main
    runAnalysisChild(aminerConfig, programName)
  File "/usr/bin/AMiner", line 97, in runAnalysisChild
    childReturnStatus = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 201, in run_analysis
    self.analysis_context.build_analysis_pipeline()
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 147, in build_analysis_pipeline
    self.aminer_config.build_analysis_pipeline(self)
  File "/tmp/demo-config.py", line 180, in build_analysis_pipeline
    MultiLocaleDateTimeModelElement('MultiLocaleDateTimeModelElement', [(b'%b %d %Y', "de_AT.utf8", None)]))
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/MultiLocaleDateTimeModelElement.py", line 67, in __init__
    self.date_formats.add_format(format_string, format_locale, format_timezone)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/MultiLocaleDateTimeModelElement.py", line 222, in add_format
    locale.setlocale(locale.LC_ALL, format_locale)
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by skopikf** [comment]
locale was set to en_US.utf8 on the test system where the above referenced error occured.
Error disappears after setting locale to de_AT.utf8.

However, the question is if it is advisable at all to depend on such a specific locale -- for what part of the Demo is the locale setting actually important?

**Comment by dITySoftware** [comment]
fixed in PR #154.

**Comment by dITySoftware** [comment]
> locale was set to en_US.utf8 on the test system where the above referenced error occured.
> Error disappears after setting locale to de_AT.utf8.
> 
> However, the question is if it is advisable at all to depend on such a specific locale -- for what part of the Demo is the locale setting actually important?

I think the locale just needs to be installed. It is used by the MultiLocaleDateTimeModelElement. The fix uses the current locale setting of the system.
