### ISSUE TITLE
Z in timestamp

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1306]
A common timestamp format is "2024-03-21T20:46:06.955Z", which has the "Z" in the end, representing UTC. I do not think that this is currently supported to be parsed with our %z format. Also, this sample should be included in the aminer documentation as it is very common.

**Comment by ernstleierzopf** [comment]
This can easily be represented using a format such as "%Y-%m-%dT%H:%M:%S.%fZ". However, I extended the %z format to also include parsing Z specifically to improve usability.
