### ISSUE TITLE
Numpy linking issue

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1311]
When installing the aminer with aminer_install script, numpy and other packages are linked as follows:

numpy -> /usr/lib/python3/dist-packages/pythran/pythonic/include/numpy

This is not correct as they should be linked to /usr/lib/python3/dist-packages/numpy

**Comment by landauermax** [comment]
Tested on:

Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic

**Comment by ernstleierzopf** [comment]
I fixed this by removing recursive search in the linking part in aminer-ansible and created pull requests for the development and the main branches. I also tested it and think it works.
@landauermax you can test this by simply exchanging the aminer-ansible repository to git clone -b fix_linking https://github.com/ernstleierzopf/aminer-ansible roles/aminer.
@whotwagner please check the changes/results with @landauermax and merge these changes to the aminer-ansible project.

**Comment by ernstleierzopf** [comment]
This PR was accepted in the aminer-ansible project. Closing the issue.
