### ISSUE TITLE
Missing timestamp warning for unparsed logs

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1324]
The warning "No timestamp was found for a log_atom" is generated when unparsed events occur. I dont think that a warning should occur in this case, because it can be confusing - users will start looking for reasons why the timestamp is not there even though the line itself is the problem. An unparsed event is an anomaly and cannot be treated like an normal line anyway.

**Comment by ernstleierzopf** [comment]
This message is printed in the ByteStreamLineAtomizer before the log atom is parsed. Therefore the message can not be filtered out if the atom can not be parsed. However, I extended the error message to include alternatives such as using the use_real_time or continuous_timestamp_missing_warning parameters to only show this message once.
