### ISSUE TITLE
Improve Error output when file input specifier is missing

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#1338]
When missing the `file:` specifier in the LogResourceList, the current error looks like: 

`Unsupported schema in LogResourceList: {'url': b'/home/landauerm/videoserver/logs/error.log.1', 'parser_id': 'ApacheErrorParsingModel', 'json': None, 'xml': None}`

It is not obvious from this error that the url should look like `file:///home/landauerm/videoserver/logs/error.log.1` instead. The error message should be improved to make this clear, since it is very easy to miss the specifier.

**Comment by ernstleierzopf** [comment]
Changed the error message to the following:
Config-Error: {'LogResourceList': 'Every log resource URL must be prefixed with either file:// or unix://.'}
