### ISSUE TITLE
Make aminer ready for Debian Bullseye 

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#143]
- [x] Test aminer-ansible-role on Debian Bullseye

- [x] Install aminer

- [x] Run aminer-tests

- [x] Run aminer configs

- [x] Test Getting-Started

**Comment by dITySoftware** [comment]
`# These are only the commands used. They cannot be used as a script directly.
# run in Debian "Bullseye" Alpha 2

apt install sudo # run this as root
nano /etc/sudoers # append user  ALL=(ALL) NOPASSWD:ALL

wget https://www.python.org/ftp/python/3.6.12/Python-3.6.12.tgz
tar xvf Python-3.6.12.tgz
cd Python-3.6.12
./configure --enable-optimizations
# make -j8 - gets stuck at test 125.. (not finishing even after 4h)
make -j8 build_all # use this instead
sudo make altinstall
cd ..
git clone https://github.com/ait-aecid/logdata-anomaly-miner.git
cd logdata-anomaly-miner/

# Debian Bullseye does not offer python3.6 by default. All packages have to be linked into the python3.6 directory for aminer-ansible to work.
sudo mkdir /usr/lib/python3.6
sudo mkdir /usr/lib/python3.6/site-packages
sudo ln -s /usr/local/lib/python3.8/dist-packages/cerberus /usr/lib/python3.6/site-packages/cerberus
sudo ln -s /usr/local/lib/python3.8/dist-packages/kafka /usr/lib/python3.6/site-packages/kafka
nano ./scripts/aminer_install.sh # change BRANCH to development
sudo ./scripts/aminer_install.sh
sudo apt-get install -y exim4 procps cpulimit mailutils curl default-jre # default-jre is needed for kafka
sudo pip3 install coverage
sudo cp $PWD/source/root/etc/aminer/conf-available/generic/ApacheAccessModel.py /etc/aminer/conf-enabled/ApacheAccessModel.py
ln -s $PWD/source/root/usr/lib/logdata-anomaly-miner/aminer $PWD/aecid-testsuite/aminer
ln -s $PWD/source/root/etc/aminer/template_config.py $PWD/aecid-testsuite/demo/AMiner/template_config.py
cd aecid-testsuite
sudo chmod +x runUnittests.sh
sudo chmod +x runAMinerDemo.sh
sudo chmod +x runAMinerIntegrationTest.sh
sudo chmod +x runCoverageTests.sh
sudo dpkg-reconfigure locales # install de_AT.UTF-8, en_GB.UTF-8 and change de_AT.UTF-8 to default
export TZ=de_AT.UTF-8 # here i am not sure what worked, but the timezone needs to be de_AT.UTF-8!
nano /home/user/logdata-anomaly-miner/aecid-testsuite/unit/events/DefaultMailNotificationEventHandlerTest.py # change mail_call = 'echo p | mail -u mail' -> change mail_call = 'echo p | mail -u user'
./runUnittests.sh # YamlConfigTest fails as this is currently WIP.
./runCoverageTests # YamlConfigTest fails as this is currently WIP.
./runAMinerDemo.sh demo/AMiner/demo-config.py # no errors
./runAMinerDemo.sh demo/AMiner/jsonConverterHandler-demo-config.py # no errors
./runAMinerDemo.sh demo/AMiner/template_config.py # no errors
./runAMinerIntegrationTest.sh aminerIntegrationTest.sh config.py # no errors
./runAMinerIntegrationTest.sh aminerIntegrationTest2.sh config21.py config22.py # no errors`

**Comment by whotwagner** [comment]
You installed python from  source. We need to make sure that AMiner runs with the debian-python. If that's not possible, we have to make AMiner ready for python 3.8.2

**Comment by dITySoftware** [comment]
> You installed python from source. We need to make sure that AMiner runs with the debian-python. If that's not possible, we have to make AMiner ready for python 3.8.2

Debian Bullseye does not install python3.6 any more. aminer-ansible uses python3.6. I don't actually think there is an problem with the aminer using python3.8 or greater as I am using this the whole time and it works.

**Comment by dITySoftware** [comment]
Following lines are problematic:
```
- name: Link python3-cerberus
  file:
    src: /usr/lib/python3.6/site-packages/cerberus
    dest: /etc/aminer/conf-enabled/cerberus
    state: link
```
I have deleted python3.6 and ran the tests again without errors.

**Comment by dITySoftware** [comment]
I would not raise the minimal supported python version as it runs with python3.6 and newer without any problems.

**Comment by whotwagner** [comment]
I will fix the role

> Following lines are problematic:
> 
> ```
> - name: Link python3-cerberus
>   file:
>     src: /usr/lib/python3.6/site-packages/cerberus
>     dest: /etc/aminer/conf-enabled/cerberus
>     state: link
> ```
> 
> I have deleted python3.6 and ran the tests again without errors.
