### ISSUE TITLE
Flag for stat file

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#149]
Write a statistics file, e.g, how many log lines processed, or advanced statistics from detectors.

Flag with different levels, similar to debug output

**Comment by dITySoftware** [comment]
for statistics i could think of two levels: normal and verbose. The normal level provides information like how many lines were processed in the last period measured time, how many unparsed atoms occured (same for verbose handler).

The verbose level could additionally provide information about how many log atoms were successfully processed by every analysis component (for example when the return of receive_atom was True).

Also an important question is if the statistics file should be used like a log, where every period of time a new line is added, or if the statistics should be overwritten incrementally for the whole time.

**Comment by landauermax** [comment]
I think it is a good starting point. Detector statistics could include the number of rules, values, paths, learned during a time interval or in total. It should definitely store the events as logs.

**Comment by dITySoftware** [comment]
maybe there also should be an option for no statistic output.

**Comment by landauermax** [comment]
Yes of course.

**Comment by dITySoftware** [comment]
implemented in PR #205.
