### ISSUE TITLE
Add missing ParsingModelElements to documentation

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#150]
Add missing ParsingModelElements here https://github.com/ait-aecid/logdata-anomaly-miner/blob/master/source/root/usr/share/doc/logdata-anomaly-miner/aminer/ParsingModel.txt.

**Comment by dITySoftware** [comment]
I have checked this issue. There are currently no missing ParsingModelElements.
Please close this issue.
