### ISSUE TITLE
ymlconfig: catch import errors for analysis-components via schema-validation

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#161]
An AnalysisType is defined in  Configvalidator.py. This type is not in use yet. By using it in yamlconfig.py import errors for analysis-components can be handled by the schema validation.

In addition, unit-tests for the AnalysisType must be created(see ParserModelType)

**Comment by dITySoftware** [comment]
I have avoided the import errors by defining every needed import in __init__.py. Should the current solution be changed to use the AnalysisType. If yes, how else would every Detector be whitelisted in the AnalysisType?

**Comment by dITySoftware** [comment]
added the analysistype from the ConfigValidator to the schema and adapted the ymlconfig.

**Comment by dITySoftware** [comment]
can be closed after PR #165 is reviewed.

**Comment by dITySoftware** [comment]
Please move this issue to Done.
