### ISSUE TITLE
ymlconfig: unit-tests for SimpleMultisourceAtomSync and SimpleByteStreamLineAtomizerFactory

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#163]
Currently there are no unit-tests for SimpleMultisourceAtomSync and SimpleByteStreamLineAtomizerFactory in the yamlconfig.

**Comment by dITySoftware** [comment]
added in PR #165.
There also was an error in which the default_timestamp_paths were set to strings instead of the expected lists. Fixed that also.
