### ISSUE TITLE
ymlconfig: Create support for EventHandlerType 

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#167]
In ConfigValidator we have custom-types for ParserModelType and AnalysisType. We also need an EventHandlerType in order to catch import-errors during schema-validation.

In addition we need unit-tests in order to make sure that the import works and that the errors are caught properly

**Comment by dITySoftware** [comment]
added all EventHandlers in PR #165.

**Comment by dITySoftware** [comment]
added eventhandlertype in the ConfigValidator and schema.

**Comment by dITySoftware** [comment]
can be closed after accepting PR #165.
