### ISSUE TITLE
Bugfix: unit-tests with random-values fail occasionally

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#173]
The EventCorrelationDetectorTest.py randomly fails. It seems to me that at least one test uses random values. We need deterministic tests. The input values need to be specified so that we can expect a specific output.

**Comment by dITySoftware** [comment]
The ECD has properties like generation_probability and generation_factor, which are based on randomness. Due to that the detector itself is not deterministic. I tried to increase the datasizes to be able to test these cases accurately.

**Comment by dITySoftware** [comment]
i have run the unittests for the ecd 100 times without errors. There still is a possibility of the tests failing as the ecd is not deterministic when using randomness parameters.

Please close this issue after reviewing PR #174.
