### ISSUE TITLE
Add suspend mode.

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#180]
When AMiner runs as a service, it should be possible to pause and resume the AMiner via remote control.

**Comment by dITySoftware** [comment]
The AMinerRemoteControl sends commands, which are basically executed in AMinerRemoteControlExecutionMethods.py.

If the process is suspended, there is actually no way for the AMinerRemoteControl to communicate with the AMiner or to reactivate it.

One way to implement this functionality is to create a flag (i. e. suspended_flag) and to let the aminer process sleep for short periods (for example 1 second) in a loop, which checks the suspension flag. Is this the way to go?

**Comment by whotwagner** [comment]
Is it possible to use the current analysis-loop for that. And we just add a suspended_flag that makes sure that this loop has a dry-run?

**Comment by dITySoftware** [comment]
implemented in PR #195.

Test example:
sudo AMiner --Foreground --Config /tmp/demo-config.py # start aminer

echo test >> /tmp/syslog # prints output
sudo AMinerRemoteControl --Exec "suspend" # suspend aminer
echo test1 >> /tmp/syslog # no output printed
sudo AMinerRemoteControl --Exec "activate" # activate aminer
# output is printed.
