### ISSUE TITLE
Fix missing detector persistency handling

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#208]
Some detectors, e.g., the MatchValueAverageChangeDetector, have on working persistency (not stored and/or read). This needs to be fixed for all detectors.

**Comment by dITySoftware** [comment]
HistogramAnalysis does not persist any data. Does that happen on purpose?

**Comment by dITySoftware** [comment]
Should the TimeCorrelationDetector actually support persistence? 
It would be nessecary to serialize CorrelationFeature and Rules.AndMatchRule, Rules.PathExistsMatchRule and Rules.ValueMatchRule.

**Comment by dITySoftware** [comment]
I have added all missing persistence handling and testet by running the aminer demo with a sleep(600) before killing the process. This is better than normally shutting down the aminer as it also tests the do_timer method.

The aminer was started with
`aminer --Foreground --Config /tmp/demo-config.py`
to test the stability.

All tests were successful.

**Comment by landauermax** [comment]
> 
> 
> HistogramAnalysis does not persist any data. Does that happen on purpose?

I think that is because the component is mainly intended for creating live reports rather than anomaly detection. We can argue that therefore there is no need for persisting any data.

**Comment by landauermax** [comment]
> 
> 
> Should the TimeCorrelationDetector actually support persistence?
> It would be nessecary to serialize CorrelationFeature and Rules.AndMatchRule, Rules.PathExistsMatchRule and Rules.ValueMatchRule.
> 
> Same or worse in the TimeCorrelationViolationDetector..

I think a solution could be to only persist the id of the rule, and assume that the same rules are available in the following aminer executions. But that may be too complex, so if it requires too many workarounds let us skip it for now.
