### ISSUE TITLE
ymlconfig: Add stat and debug configurations

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#221]
Pullrequest #205 adds stat and debug functionality to the aminer. The config-parameters for debug and stat must also be configurable via yamlconfig.

**Comment by dITySoftware** [comment]
These parameters are not even configurable by the python config. They are set at program startup.
I can't think of configuring this in the config file.. However maybe it should be possible to change them via remote control.

**Comment by dITySoftware** [comment]
Please link this issue to PR #205
