### ISSUE TITLE
Refatcor Count Report

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#234]
In Count report, it is not clear that the status info reports the number of processed lines. Fix by adding a 'lines' as label. Always show lines processed in the last tw and totally processed lines, for example, <lines last tw> (<total lines>).

**Comment by landauermax** [comment]
Could you provide an example? I am not sure if I understand it correct. Should it look like this:

Count report (1 lines)
{
  "StatusInfo": {
    "Lines": {
      "/parser/model/status_code": {
        "Current": 97476,
        "Total": 429054
      },
      "/parser/model/php": {
        "Current": 345,
        "Total": 6553
      }
    }
  },
  "FromTime": 1596457890.205487,
  "ToTime": 1596457900.205512
}

**Comment by 4cti0nfi9ure** [comment]
Change current to Processed lines; add the option to configure a label that is shown instead of the path.

**Comment by 4cti0nfi9ure** [comment]
Add parameter to split count report into seperate objects for each log source.

**Comment by dITySoftware** [comment]
> In Count report, it is not clear that the status info reports the number of processed lines. Fix by adding a 'lines' as label. Always show lines processed in the last tw and totally processed lines, for example, ().

This would make the reset_after_report_flag deprecated and useless. With this flag it is possible to reset the numbers after each report. Why would anyone want to reset it if there is a total and current count.

**Comment by landauermax** [comment]
Yes, the flag can be removed.

**Comment by dITySoftware** [comment]
In the following example the two paths ['/model/ECD/a', '/model/ECD/b'] with the labels ['A', 'B'] were used.
The json output with split_reports_flag=False looks like this:
Count report (1 lines)
  {
  "StatusInfo": {
    "A": {
      "CurrentProcessedLines": 0,
      "TotalProcessedLines": 1667
    },
    "B": {
      "CurrentProcessedLines": 0,
      "TotalProcessedLines": 1667
    }
  },
  "FromTime": 1605012778.694775,
  "ToTime": 1605012788.694795
}

The output with split_reports_flag=True looks like this:
Count report (1 lines)
  {
  "StatusInfo": {
    "A": {
      "CurrentProcessedLines": 854,
      "TotalProcessedLines": 854
    }
  },
  "FromTime": 1605013015.025105,
  "ToTime": 1605013025.025114
}

Count report (1 lines)
  {
  "StatusInfo": {
    "B": {
      "CurrentProcessedLines": 854,
      "TotalProcessedLines": 854
    }
  },
  "FromTime": 1605013015.025311,
  "ToTime": 1605013025.025315
}
