### ISSUE TITLE
Refactor and standardize command line parameters

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#242]

**Comment by dITySoftware** [comment]
Are the aminer and aminerremotecontrol command line parameters meant?

**Comment by landauermax** [comment]
No, this issue is about the aminer command line parameters, such as --Config

**Comment by dITySoftware** [comment]
Okay and what is wrong with them? I have already added multiple options for every parameter.

**Comment by landauermax** [comment]
It is mainly that it is not clear when lowercase and uppercase should be used. @whotwagner originally proposed that this is an issue, therefore he is also assigned to it.

**Comment by dITySoftware** [comment]
Well both options are currently valid. Also most of the times there is an short option with only one -.

**Comment by whotwagner** [comment]
There are best practices like orienting on the postix-standard(https://softwareengineering.stackexchange.com/questions/307467/what-are-good-habits-for-designing-command-line-arguments) and on the apache-cli( https://commons.apache.org/proper/commons-cli/ )

I would suggest to use a short and a long parameter. the short can be a Lower or Upper-case letter. The long should be lowercaseletters where words are connectd by a hyphen. We definitly want "--version and --help". 

Beside that, I would recommend to use th argparse: https://docs.python.org/3/library/argparse.html
this library helps to also define what argument(-types) we expect. like number from 1-10 or string or whatever...
