### ISSUE TITLE
Make template configs part of testing

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#252]
It would be good to copy the configs and executing them to look for errors in travis. For example, the parsing model in the template config https://github.com/ait-aecid/logdata-anomaly-miner/blob/master/source/root/etc/aminer/template_config.py

does not exist anymore.

**Comment by landauermax** [comment]
Sorry, the parsing model is located in generic.

**Comment by dITySoftware** [comment]
it also is tested with the aminerDemo - see .travis.yml for that

**Comment by landauermax** [comment]
But it is just template_conf.py, and not template_conf.yml, right? Can we add the yml config as well?

**Comment by dITySoftware** [comment]
sure. Reopen this Issue.
