### ISSUE TITLE
Add debian stretch  support for yaml config

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#256]

**Comment by dITySoftware** [comment]
Please define what the problem is. Was anything tested on debian stretch? Why does the yaml config specifically not work in debian strech?

**Comment by landauermax** [comment]
We got the following error with the standard config:
root@mail:/usr/lib/logdata-anomaly-miner/aminer# aminer --config /etc/aminer/config.yml
Config-Error: {'EventHandlers': [{0: [{'type': ["field 'type' cannot be coerced: cannot import name 'multinomial'"]}]}]}

**Comment by dITySoftware** [comment]
i will look into it.

**Comment by dITySoftware** [comment]
do you know if it was only in debian strech? or is this an general problem?

**Comment by landauermax** [comment]
We think it is a version-specific, it should work on the newer versions and only occur in strech and older - but we have not tested this in detail yet.

**Comment by dITySoftware** [comment]
Do you have the system already installed and could test one simple step for me?

**Comment by landauermax** [comment]
Yes should be possible.

**Comment by dITySoftware** [comment]
actually please first show me the config used in the setup.

**Comment by dITySoftware** [comment]
also please show all links in /etc/aminer/conf-enabled
seems that scipy is not available.

**Comment by landauermax** [comment]
`
LearnMode: True
AMinerUser: 'aminer'
AMinerGroup: 'aminer'

LogResourceList:
        - 'file:///var/log/daemon.log'
        - 'file:///var/log/auth.log'
        - 'file:///var/log/suricata/eve.json'
        - 'file:///var/log/suricata/fast.log'
        - 'file:///var/log/apache2/mail.thermometer.com-access.log'
        - 'file:///var/log/apache2/mail.thermometer.com-error.log'
        - 'file:///var/log/exim4/mainlog'
        - 'file:///var/log/syslog'
        - 'file:///var/log/audit/audit.log'

Core.PersistenceDir: '/var/lib/aminer'

Parser:
        - id: 'auditModel'
          type: AuditdParsingModel
          name: 'audit'
          args: 'audit'

        - id: 'suricataEventModel'
          type: SuricataEventParsingModel
          name: 'suricataEvent'
          args: 'suricataEvent'

        - id: 'syslogModel'
          type: SyslogParsingModel
          name: 'syslog'
          args: 'syslog'

        - id: 'apacheAccessModel'
          type: ApacheAccessParsingModel
          name: 'apacheAccess'
          args: 'apacheAccess'

        - id: 'apacheErrorModel'
          type: ApacheErrorParsingModel
          name: 'apacheError'
          args: 'apacheError'

        - id: 'eximModel'
          type: EximParsingModel
          name: 'exim'
          args: 'exim'

        - id: 'suricataFastModel'
          type: SuricataFastParsingModel
          name: 'suricataFast'
          args: 'suricataFast'

        - id: 'START'
          start: True
          type: FirstMatchModelElement
          name: 'parser'
          args:
            - auditModel
            - suricataEventModel
            - syslogModel
            - apacheAccessModel
            - apacheErrorModel
            - eximModel
            - suricataFastModel

Input:
        verbose: True
        multi_source: True
        timestamp_paths:
          - '/parser/model/time'
          - '/parser/model/type/execve/time'
          - '/parser/model/type/proctitle/time'
          - '/parser/model/type/syscall/time'
          - '/parser/model/type/path/time'
          - '/parser/model/type/login/time'
          - '/parser/model/type/sockaddr/time'
          - '/parser/model/type/unknown/time'
          - '/parser/model/type/cred_refr/time'
          - '/parser/model/type/user_start/time'
          - '/parser/model/type/user_acct/time'
          - '/parser/model/type/user_auth/time'
          - '/parser/model/type/cred_disp/time'
          - '/parser/model/type/service_start/time'
          - '/parser/model/type/service_stop/time'
          - '/parser/model/type/user_end/time'
          - '/parser/model/type/cred_acq/time'
          - '/parser/model/type/user_bprm_fcaps/time'

Analysis:

EventHandlers:
        - id: 'stpe'
          json: True # optional default: False
          typer: 'StreamPrinterEventHandler'
`

**Comment by landauermax** [comment]
root@mail:/usr/lib/logdata-anomaly-miner/aminer# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

**Comment by landauermax** [comment]
root@mail:/usr/lib/logdata-anomaly-miner/aminer# ls -al /etc/aminer/conf-enabled/
total 116
drwxr-xr-x 2 root root  4096 Nov 10 15:06 .
drwxr-xr-x 4 root root  4096 Nov 11 09:43 ..
-rw-r--r-- 1 root root  2663 Nov 10 15:06 ApacheAccessParsingModel.py
-rw-r--r-- 1 root root  3858 Nov 10 15:06 ApacheErrorParsingModel.py
-rw-r--r-- 1 root root 20197 Nov 10 15:06 AuditdParsingModel.py
lrwxrwxrwx 1 root root    47 Nov 10 15:05 cerberus -> /usr/local/lib/python3.5/dist-packages/cerberus
lrwxrwxrwx 1 root root    39 Nov 10 15:05 dateutil -> /usr/lib/python3/dist-packages/dateutil
-rw-r--r-- 1 root root  6462 Nov 10 15:06 EximParsingModel.py
lrwxrwxrwx 1 root root    44 Nov 10 15:05 kafka -> /usr/local/lib/python3.5/dist-packages/kafka
lrwxrwxrwx 1 root root    36 Nov 10 15:05 numpy -> /usr/lib/python3/dist-packages/numpy
lrwxrwxrwx 1 root root    52 Nov 10 15:05 pkg_resources -> /usr/local/lib/python3.5/dist-packages/pkg_resources
lrwxrwxrwx 1 root root    35 Nov 10 15:05 pytz -> /usr/lib/python3/dist-packages/pytz
-rw-r--r-- 1 root root   458 Nov 10 15:05 Readme.txt
lrwxrwxrwx 1 root root    36 Nov 10 15:05 scipy -> /usr/lib/python3/dist-packages/scipy
lrwxrwxrwx 1 root root    37 Nov 10 15:05 six.py -> /usr/lib/python3/dist-packages/six.py
-rw-r--r-- 1 root root 34248 Nov 10 15:06 SuricataEventParsingModel.py
-rw-r--r-- 1 root root  1736 Nov 10 15:06 SuricataFastParsingModel.py
-rw-r--r-- 1 root root 28535 Nov 10 15:06 SyslogParsingModel.py
lrwxrwxrwx 1 root root    35 Nov 10 15:05 yaml -> /usr/lib/python3/dist-packages/yaml

**Comment by dITySoftware** [comment]
Please show me the scipy version by running `dpkg -s python3-scipy`

**Comment by landauermax** [comment]
root@mail:/usr/lib/logdata-anomaly-miner/aminer# dpkg -s python3-scipy
Package: python3-scipy
Status: install ok installed
Priority: extra
Section: python
Installed-Size: 33614
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: amd64
Source: python-scipy
Version: 0.18.1-2
Depends: python3-decorator, python3-numpy (>= 1:1.10.0~b1), python3-numpy-abi9, python3 (<< 3.6), python3 (>= 3.5~), python3:any (>= 3.3.2-2~), libblas3 | libblas.so.3, libc6 (>= 2.14), libgcc1 (>= 1:4.0), libgfortran3 (>= 4.6), liblapack3 | liblapack.so.3, libquadmath0 (>= 4.6), libstdc++6 (>= 5.2)
Recommends: g++ | c++-compiler
Suggests: python-scipy-doc
Description: scientific tools for Python 3
 SciPy supplements the popular NumPy module (python-numpy package), gathering a
 variety of high level science and engineering modules together as a single
 package.
 .
 SciPy is a set of Open Source scientific and numeric tools for Python. It
 currently supports special functions, integration, ordinary differential
 equation (ODE) solvers, gradient optimization, genetic algorithms, parallel
 programming tools, an expression-to-C++ compiler for fast execution, and
 others.
 .
 This package provides the Python 3 version.
Homepage: http://www.scipy.org/

**Comment by dITySoftware** [comment]
> root@mail:/usr/lib/logdata-anomaly-miner/aminer# dpkg -s python3-scipy
> Package: python3-scipy
> Status: install ok installed
> Priority: extra
> Section: python
> Installed-Size: 33614
> Maintainer: Debian Python Modules Team [python-modules-team@lists.alioth.debian.org](mailto:python-modules-team@lists.alioth.debian.org)
> Architecture: amd64
> Source: python-scipy
> Version: 0.18.1-2
> Depends: python3-decorator, python3-numpy (>= 1:1.10.0~b1), python3-numpy-abi9, python3 (<< 3.6), python3 (>= 3.5~), python3:any (>= 3.3.2-2~), libblas3 | libblas.so.3, libc6 (>= 2.14), libgcc1 (>= 1:4.0), libgfortran3 (>= 4.6), liblapack3 | liblapack.so.3, libquadmath0 (>= 4.6), libstdc++6 (>= 5.2)
> Recommends: g++ | c++-compiler
> Suggests: python-scipy-doc
> Description: scientific tools for Python 3
> SciPy supplements the popular NumPy module (python-numpy package), gathering a
> variety of high level science and engineering modules together as a single
> package.
> .
> SciPy is a set of Open Source scientific and numeric tools for Python. It
> currently supports special functions, integration, ordinary differential
> equation (ODE) solvers, gradient optimization, genetic algorithms, parallel
> programming tools, an expression-to-C++ compiler for fast execution, and
> others.
> .
> This package provides the Python 3 version.
> Homepage: http://www.scipy.org/

Thanks. So here lies the problem! See the notes here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multinomial.html
scipy.stats.multinomial is new in scipy version 0.19.0

**Comment by dITySoftware** [comment]
Are all packages up to date? If yes try to run following commands:
sudo rm /etc/aminer/conf-enabled/numpy
sudo rm /etc/aminer/conf-enabled/scipy
sudo pip3 install scipy
sudo ln -s {scipy-location} /etc/aminer/conf-enabled/scipy
sudo ln -s {numpy-location} /etc/aminer/conf-enabled/numpy
sudo chown -R aminer:aminer /etc/aminer

**Comment by landauermax** [comment]
That solved the problem. Thanks!
