### ISSUE TITLE
YAML support for event handler selection

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#265]
It would be beneficial to assign the detectors the id of the event handlers where they should output their anomalies. For example, a detector that is only used for forwarding (MatchFilter) should report anomalies only to a specific Kafka Handler with a certain topic. The idea is to specifiy the ids of the event handlers in a specific (optional) field, such as event_handlers: stpe, etc. When no event_handlers are specified, the anomalies should be reported to all available event handlers.

**Comment by dITySoftware** [comment]
This issue cannot be fixed yet. Please accept PR #255 first.

**Comment by dITySoftware** [comment]
Waiting for PR #279 to be accepted.
