### ISSUE TITLE
Remote Control error on debian

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#275]
We encountered the following error on debian stretch. The command is successful, but something seems to be wrong with the response.

root@mail:~# python3 /usr/lib/logdata-anomaly-miner/aminerremotecontrol.py --Exec  "print_attribute_of_registered_analysis_component(analysis_context, 'ParserCount1',  'report_interval')"
Failed to process response b'\x00\x00\x005RRRR[null, "\\"ParserCount1.report_interval\\": 1"]'
Traceback (most recent call last):
  File "/usr/lib/logdata-anomaly-miner/aminerremotecontrol.py", line 127, in <module>
    remote_data = json.loads(request_data[8:])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by dITySoftware** [comment]
No aminer bug. Use an newer python version.
json.loads supports bytes-Objects since python3.6
https://docs.python.org/3/library/json.html

**Comment by landauermax** [comment]
Alright, thanks for the info!
