### ISSUE TITLE
Enable remote control for yaml config

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#276]
There does not seem to be an option to set the remote control socket in the yaml config.

The demo tests should be extended accordingly to also test the remote control with the yaml config.

**Comment by dITySoftware** [comment]
The remote control is initialized in AnalysisChild. It has nothing to do with the yaml config (neither with the AMinerConfig).

Have you tested the described error? Does an error occur when running aminer with yaml configs and an remote control command was executed?

**Comment by landauermax** [comment]
In https://github.com/ait-aecid/logdata-anomaly-miner/blob/master/aecid-testsuite/demo/AMinerRemoteControl/demo-config.py there is the attribute config_properties['RemoteControlSocket'] = '/var/run/aminer-remote.socket', so there must be a connection between the remote control and the config. There does not seem to be an option to set the remote control socket in the yaml config.

**Comment by dITySoftware** [comment]
Ok, sorry I missread.
Please accept PR #255 first.

**Comment by dITySoftware** [comment]
Waiting for PR #279 to be accepted.
