### ISSUE TITLE
aminerremotecontrol command raises dateutil error

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#277]
Tested on debian stretch. When executing using /usr/lib/logdata-anomaly-miner/aminerremotecontrol.py, the remote control works. Maybe a linking issue?

root@mail:/home/debian# aminerremotecontrol
Traceback (most recent call last):
  File "/usr/bin/aminerremotecontrol", line 38, in <module>
    from aminer.AnalysisChild import AnalysisChildRemoteControlHandler
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 30, in <module>
    from aminer.input.LogStream import LogStream
  File "/usr/lib/logdata-anomaly-miner/aminer/input/__init__.py", line 2, in <module>
    from aminer.input.ByteStreamLineAtomizer import ByteStreamLineAtomizer
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 17, in <module>
    from aminer.parsing import MatchContext
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/__init__.py", line 4, in <module>
    from aminer.parsing.DateTimeModelElement import DateTimeModelElement
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py", line 19, in <module>
    from dateutil.parser import parse
ImportError: No module named 'dateutil'

**Comment by dITySoftware** [comment]
> Tested on debian stretch. When executing using /usr/lib/logdata-anomaly-miner/aminerremotecontrol.py, the remote control works. Maybe a linking issue?
> 
> root@mail:/home/debian# aminerremotecontrol
> Traceback (most recent call last):
> File "/usr/bin/aminerremotecontrol", line 38, in
> from aminer.AnalysisChild import AnalysisChildRemoteControlHandler
> File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 30, in
> from aminer.input.LogStream import LogStream
> File "/usr/lib/logdata-anomaly-miner/aminer/input/**init**.py", line 2, in
> from aminer.input.ByteStreamLineAtomizer import ByteStreamLineAtomizer
> File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 17, in
> from aminer.parsing import MatchContext
> File "/usr/lib/logdata-anomaly-miner/aminer/parsing/**init**.py", line 4, in
> from aminer.parsing.DateTimeModelElement import DateTimeModelElement
> File "/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py", line 19, in
> from dateutil.parser import parse
> ImportError: No module named 'dateutil'

Yes I think it is a linking issue.
Run something like:
```
find /usr -name dateutil
sudo ln -s {found_path} /etc/aminer/conf-enabled/dateutil
```

**Comment by dITySoftware** [comment]
Is this still an issue or did you already solve it?

**Comment by landauermax** [comment]
Thanks for the reminder, I forgot to resolve the issue. Yes, it was fixed by linking.
