### ISSUE TITLE
Text file output component

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#287]
Similar to streamPrinter and syslog output component, there should be an output component that writes the anomalies to a simple text file.

**Comment by dITySoftware** [comment]
This is already implemented with the StreamPrinterEventHandler. Just define the stream with a file handler.
Close if you agree.

**Comment by dITySoftware** [comment]
Also redirecting (with > or >>) is a core linux mechanic which also works for that task.

**Comment by landauermax** [comment]
The problem is that the yaml config does not support defining file handler as streams, therefore, we need some mechanism (can be added to the streamprintereventhandler) that allows this functionality. Redirecting with > is not possible when the aminer is started as a service.

**Comment by dITySoftware** [comment]
Okay i have added a new PR.
