### ISSUE TITLE
Add overall output for aminer

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#288]
There should be a way to write everything that the AMiner outputs in a file. For example, in the beginning of the config, a parameter StandardOutput: "/etc/aminer/output.txt" can be set, where all the output (anomalies, errors, etc) is written to in addition to the usual output components. By default, it should be None and not write anything.

**Comment by dITySoftware** [comment]
Same as in issue #287 this can be handled with > or >> or 2> depending on the stream you want to redirect.
If you want both cases to be covered - printing to stdout and printing to file - you have to define two StreamPrinterEventHandlers and set the streams there.

**Comment by dITySoftware** [comment]
Please close if you agree.

**Comment by landauermax** [comment]
The problem is that output components do not write error messages, e.g., when the aminer crashes due to some bug, to the file, and > is not possible when the aminer is run as a service.

**Comment by dITySoftware** [comment]
I think in that case the (debug) logfile provides or should provide (every error message should be checked again after all PR are accepted - there already exists an issue for that) the output errors. Error messages are logged at every log level.

**Comment by landauermax** [comment]
Does this include exceptions thrown by python? For example, there is an index out of bound exception in one of the detectors and we do not catch this exception, will the message end up in the aminer logfile?

**Comment by dITySoftware** [comment]
It includes every catched error, but I think the answer is no. If the error is not catched, it is not logged.

**Comment by dITySoftware** [comment]
However i think this is a common problem and should not be solved in code. 
For systemd here is the answer - instead or additionally to StandardOutput you can also define StandardError. See here for the answer: https://unix.stackexchange.com/questions/408929/systemd-how-to-redirect-stdout-to-logfile

**Comment by dITySoftware** [comment]
Where is the systemd service defined? Is it in the repository? If so i can make the changes.

**Comment by dITySoftware** [comment]
> Where is the systemd service defined? Is it in the repository? If so i can make the changes.

I have found it in source/root/lib/systemd/system.
StandardOutput is set to null. Is there a reason for this?
StandardError can also be defined to a specific file.

What file should be used by default (for both?)? /var/lib/aminer/aminer.log?

**Comment by dITySoftware** [comment]
We have discussed this and will implement it in the service configuration.
