### ISSUE TITLE
Test persistency loading and writing

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#289]
We encountered an error of the VTD when the persistency is written, and the aminer is stopped and started again. It would be good if restarting the aminer with written persistencies is carried out purpusefully yas part of testing, probably integration testing.

**Comment by dITySoftware** [comment]
Do were really need to test persistence every single run? These tests should be run with the aminer demo as it contains all components. It would take up about 10 minutes every run.

I have run the aminer demo twice and in the second run the deleting of persistence was commented out. I could not reproduce the described problem.

Please add the configuration, aminer arguments and data used to produce the error. Also the detailled steps would be helpful in debugging this.

**Comment by landauermax** [comment]
@hoeldg is already working on a fix for the problem. But it would be good if we catch such problems already during automatic testing and not when executing the aminer manually. We also could make the persist time a parameter that is set to a lower value for testing.

**Comment by dITySoftware** [comment]
Well the persist time parameter does already exist in the PR #195.

If you could provide me some data and configuration in which the error occurs and the problem is reproducable, I can add an automated test for that. However i could not reproduce the error.
Persisting happens at least once before the aminer is shutdown.

@hoeldg please let me know which configs/data was used or which data generation script was used and the error message output. I will add an automated test if it will be useful.

**Comment by dITySoftware** [comment]
@landauermax please provide the error message. Did the error occur in the VTD?

**Comment by landauermax** [comment]
Config:
     - type: 'EventTypeDetector'
       id: 'EventTypeDetector'
       #paths: ['/parser/model/fm/request/method']

     - type: 'VariableTypeDetector'
       event_type_detector: 'EventTypeDetector'
       num_init: 200
       num_update: 100
       num_s_ks_values: 100
       num_update_unq: 200
       num_update_var_type_hist_ref: 20
       paths: ['/parser/model/fm/request/method']
       output_logline: False
       silence_output_except_indicator: True
       silence_output_without_confidence: True


Error:
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]: Traceback (most recent call last):
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 505, in <module>
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     main()
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 261, in main
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     run_analysis_child(aminer_config, program_name)
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 138, in run_analysis_child
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     child_return_status = child.run_analysis(3)
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 283, in run_analysis
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     handle_result = fd_handler_object.handle_stream()
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 360, in handle_stream
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 116, in consume_data
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     if self.dispatch_atom(log_atom):
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 133, in dispatch_atom
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     if handler.receive_atom(log_atom):
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/SimpleMultisourceAtomSync.py", line 115, in receive_atom
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     self.forward_atom(log_atom)
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/SimpleMultisourceAtomSync.py", line 126, in forward_atom
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     handler.receive_atom(log_atom)
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/analysis/AtomFilters.py", line 47, in receive_atom
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     handler_result = handler.receive_atom(log_atom)
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py", line 653, in receive_atom
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     self.process_ll(event_index, log_atom)
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py", line 821, in process_ll
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     self.update_var_type(event_index, var_index, log_atom)
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:   File "/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py", line 1295, in update_var_type
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]:     if self.var_type[event_index][var_index][0] in self.distr_list:
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]: IndexError: list index out of range
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]: sys:1: ResourceWarning: unclosed <socket object at 0x7ff42438afa8>
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]: sys:1: ResourceWarning: unclosed <socket object at 0x7ff424d127c8>
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]: aminer.py: Analysis child process 29799 terminated unexpectedly with signal 0x100
Nov 18 10:34:30 mail.thermometer.com aminer.py[29790]: sys:1: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_UNIX, type=2050, proto=0>

**Comment by dITySoftware** [comment]
Please try to delete all persisted files and restart the aminer same as before.
