### ISSUE TITLE
Errors when stopping aminer service under Debian Stretch

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#290]
Nov 16 14:53:47 mail.thermometer.com systemd[1]: Stopping AMiner log data mining server...
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: WARNING: SECURITY: Open should use O_PATH, but not yet available in python
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: WARNING: SECURITY: No secure open yet due to missing openat in python!
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: WARNING: SECURITY: No checking for backdoor access via POSIX ACLs, use "getfacl" from "acl" package to check manually.
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/suricata/eve.json, file size too small
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/suricata/fast.log, file size too small
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/daemon.log, digest changed
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/apache2/mail.thermometer.com-access.log, file size too small
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/exim4/mainlog, file size too small
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/auth.log, file size too small
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/audit/audit.log, file size too small
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/syslog, digest changed
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Not attempting to reposition on file:///var/log/apache2/mail.thermometer.com-error.log, file size too small
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: aminer.py: caught signal, shutting down
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: Traceback (most recent call last):
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 505, in <module>
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     main()
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 261, in main
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     run_analysis_child(aminer_config, program_name)
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 138, in run_analysis_child
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     child_return_status = child.run_analysis(3)
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 362, in run_analysis
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     PersistenceUtil.persist_all()
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py", line 93, in persist_allNov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     component.do_persist()
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathDetector.py", line 103, in do_persist
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     PersistenceUtil.store_json(self.persistence_file_name, list(self.known_path_set))
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py", line 124, in store_jsonNov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     fd = create_temporary_persistence_file(file_name)
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py", line 64, in create_temporary_persistence_file
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     fd = open_persistence_file('%s.tmp-%f' % (file_name, time.time()), os.O_WRONLY | os.O_CREAT | os.O_EXCL)
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py", line 44, in open_persistence_file
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     raise openOsError
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py", line 40, in open_persistence_file
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     fd = SecureOSFunctions.secure_open_file(file_name, flags)
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:   File "/usr/lib/logdata-anomaly-miner/aminer/util/SecureOSFunctions.py", line 68, in secure_open_file
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]:     return os.open(file_name, flags | os.O_NOFOLLOW | os.O_NOCTTY)
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: PermissionError: [Errno 13] Permission denied: b'/var/lib/aminer/NewMatchPathDetector/Default.tmp-1605538427.559353'
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: sys:1: ResourceWarning: unclosed <socket object at 0x7fd249d25e88>
Nov 16 14:53:47 mail.thermometer.com aminer.py[5859]: sys:1: ResourceWarning: unclosed <socket object at 0x7fd249d4ca68>
Nov 16 14:53:49 mail.thermometer.com aminer.py[5859]: aminer.py: caught signal, shutting down
Nov 16 14:53:49 mail.thermometer.com aminer.py[5859]: sys:1: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_UNIX, type=2050, proto=0>
Nov 16 14:53:49 mail.thermometer.com systemd[1]: Stopped AMiner log data mining server.

**Comment by dITySoftware** [comment]
I cannot do anything with this error messages. Please define issues with more details.

- Is the error reproducable on other systems (or is it even reproducable on the same system)?
- Did you mess with any logfiles? Seems that you deleted lines in logs after the aminer was running. If you do that, you also have to delete RepositioningData or run aminer with fromBegin flag.
- Also there is a permission error. Please fix that before running the aminer.

If changes were made to logfiles (or if they were completely deleted) these outputs are as expected and perfectly fine.

**Comment by landauermax** [comment]
The error is not reproducible. The errors about log files are known and expected, however could have something to do with the issue. The main problem seems to be that the aminer is not able to persist data when run as a service.

**Comment by dITySoftware** [comment]
> The error is not reproducible. The errors about log files are known and expected, however could have something to do with the issue. The main problem seems to be that the aminer is not able to persist data when run as a service.

Is there always an error at persisting data when the aminer is run as service or does it sometimes work?

**Comment by landauermax** [comment]
It was likely caused by manually copying the persistency for backup, causing permission problems. We will try to resolve this with the aminer-persistency tool.
