### ISSUE TITLE
VCD: Add ignore_list and constraint_list functionality

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#293]
Thanks. The same functionality should also be added to the VTD and VCD, since they also analyze all tokens.

_Originally posted by @landauermax in https://github.com/ait-aecid/logdata-anomaly-miner/issues/266#issuecomment-728785743_

**Comment by landauermax** [comment]
Note that this is related to https://github.com/ait-aecid/logdata-anomaly-miner/issues/301
