### ISSUE TITLE
Add option to surpress output of single detectors

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#295]
Add also a global option that supresses the output of the NewMatchPatchDetector.

**Comment by dITySoftware** [comment]
Should this option be in every analysis component? Is this only yaml specific?

This will be a big change in code. Also how should the surpression be deactivated? I assume that surpression should happen only during the learning phase or what is the use case?

**Comment by 4cti0nfi9ure** [comment]
The feature should be a configuration parameter in the yaml config. It should be possible to deactivate the output of a detecor. For example in a demonstration it is useful to surpress the output of the NewMatchPathDetector, not only during training.

**Comment by dITySoftware** [comment]
Implementing this feature in all analysis components would be a big change in architecture.

How about implementing surpression in the StreamPrinterEventHandler as for demo purposes other event handlers will most likely not be used? 

For example the parameter could be 'surpress' and it would be a list of event_sources. These could be the registered names, i.e. ['NewMatchPath'], if the NewMatchPathDetector was registered with that name.

**Comment by landauermax** [comment]
I think settings relevant for a specific detector should be part of that detector, not the output component. For example, it would be easy to oversee the supress in the output component and users would not understand why their detectors do not print anything.

There must be a way to map the supress parameter of a detector specified in the yaml config so that it prevents that detector from being added to the output components, without changing the architecture too much.

**Comment by dITySoftware** [comment]
> I think settings relevant for a specific detector should be part of that detector, not the output component. For example, it would be easy to oversee the supress in the output component and users would not understand why their detectors do not print anything.
> 
> There must be a way to map the supress parameter of a detector specified in the yaml config so that it prevents that detector from being added to the output components, without changing the architecture too much.

Okay thanks, you got me the right idea.

**Comment by dITySoftware** [comment]
Okay nevermind. Still don't see how it should work without actually implementing the parameter in every component. However if we combine both ideas and add the implementation to the StreamPrinterEventHandler, both problems will be solved.
