### ISSUE TITLE
Create ignore_list and constraint_list for parser tree paths

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#301]
The problem is as follows: We often have parser trees that consist of several log files, lets assume syslog, audit, and apache. The parser paths for them are as follows:
/parser/syslog, /parser/audit, /parser/apache
of course each of them has multiple children, e.g., /parser/syslog/message, /parser/syslog/service, /parser/syslog/service/pid, etc.

Since we want to configure some detectors specifically for special log sources, we have to tell the detectors which logs to analyze by specifying the paths. For example, we want to have an ECD that only analyzes events from syslog, so we configure:
- type: ECD
- constraint_list: [/parser/syslog]
so the ECD will only consider events that include the path /parser/syslog. We restricted the parser tree to a specific subtree.

Alternatively, we want to specify paths that should be excluded from analysis of a specific detector. For example, we know that audit logs are not suitable for the ECD and want to ignore them. This means that we restricted the parser tree to a specific subtree, but this time we do not explicitly state what we want to analyze, but instead what we want to ignore:
- type: ECD
- ignore_list: [/parser/audit]

Note that this is semantically different from the allow_list and block_list that we currently use. For example, saying that we allow /parser/syslog would not mean that the parser should be restricted to syslog, and also not that they should be ignored. Affected detectors are ECD, VTD, and VCD.

**Comment by dITySoftware** [comment]
I still do not understand the difference between ignore_list and block_list.
Should blocklist always stop processing (i.e. return) and ignore_list only if no path matches constraint_list?

Also if the log atom contains a path of allowed_list, it should never be blocklisted?

Some pseudo code:
```
if path in allowlist:
  process logatom
elif path in ignore_list or path in blocklist:
  return
elif path in constraint_list and path not in blocklist:
  process logatom
```
constraint_list currently is "paths" or did I understand something wrong?
