### ISSUE TITLE
Refactor VTD output

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#307]
Add information what exactly changed, e.g., the old and new distribution.

**Comment by dITySoftware** [comment]
Please specify what message does not offer enough information. (example)
Currently the message at changing is "VariableType of path '%s' changed from '%s' to '%s' after the %s-th analysed line"

**Comment by dITySoftware** [comment]
Also please always add new issues to the organisation project board.

**Comment by 4cti0nfi9ure** [comment]
@hoeldg could you please add examples from the initial implementation for single tokens, tokenindicators and eventindicators.

**Comment by dITySoftware** [comment]
please post an example here.

**Comment by hoeldg** [comment]
Es ist so, dass wir zusätzlich zu den Variablentyp auch die Verteilung angeben sollten, also statt
... VariableType of path '/path' changed from 'others' to 'nor' after the x-th analysed line
... VariableType of path '/path' changed from 'others' to 'nor' with mean 0 and standard deviation 1 after the x-th analysed line
Also mehr parameter übergeben, damit man besser nachvollziehen kann welche Verteilungen zugeordnet wurden.
Du musst, da leider zwischen den einzelnen VTs abfragen machen und die Zeile anpassen.
Bei den kontinuierlichen VTs würde ich Verteilung, Erwartungswert und Standardabweichung ausgeben (Außer bei uniform, da Verteilung, Min und Max)
Bei others und unique brauchst du nichts ändern
Bei discrete würde ich nur alle Werte+Anteil hinschreiben, bei denen der Anteil >=10% ist und die restlichen nur als Anzahl hinschreiben (A:40%, B:30% and xx other values), damit es nicht zu unübersichtlich wird.
Aufsteigend und Absteigend, kannst du den Wert hinschreiben, der die monotonie gebrochen hat
Und Statisch, den statischen Wert, aber ich glaub, dass ist im Momnet eh so implementiert.
