### ISSUE TITLE
Implement openat in secure_open_file

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#317]
I think openat is already available in python3. Please implement it or explain what the problem and expected solution is

**Comment by 4cti0nfi9ure** [comment]
There exists already an issue for this topic. See https://github.com/ait-aecid/logdata-anomaly-miner/issues/77

**Comment by dITySoftware** [comment]
> There exists already an issue for this topic. See #77

yes however these are different issues can/should be implemented in multiple pull requests. Also it is possible that some issues can be solved with newer python versions and other not. I suggest to split these issues into more specific ones.
