### ISSUE TITLE
Discuss Coverage Tests in Travis

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#326]
Coverage tests basically run all unittests again, however they measure the coverage of tests. As Travis is paid by the runtime in minutes it would be a good idea to sort out unnessecary tests. The coverage tests do not add anything to test the functionality of aminer. If somebody is interested in the coverage, he can run the script locally too.

**Comment by dITySoftware** [comment]
I would suggest to remove them from Travis, however leave the script in the aecid-testsuite.

**Comment by dITySoftware** [comment]
It should also be discussed if AnalysisComponentsPerformanceTests need to be run every time.

**Comment by whotwagner** [comment]
> It should also be discussed if AnalysisComponentsPerformanceTests need to be run every time.

I am currently considering to create an additional test-server for low-prio-tests. Where we can run tests not so frequently

**Comment by dITySoftware** [comment]
> > It should also be discussed if AnalysisComponentsPerformanceTests need to be run every time.
> 
> I am currently considering to create an additional test-server for low-prio-tests. Where we can run tests not so frequently

how would that work? Only when merging to development or something like that?

**Comment by whotwagner** [comment]
Not sure yet. Maybe on regular bases, like hourly with email-notifications if it fails. Something like that

**Comment by dITySoftware** [comment]
Isn't that going to cost more runtime than only on commit?
Removing AnalysisComponentsPerformanceTests and coverage tests would save about 15 minutes runtime every run.
