### ISSUE TITLE
VCD: rewrite and extend unittests

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/logdata-anomaly-miner#329]
- Test if the correlation are tested in the right way with different values for max_dist_rule_distr
- Test if the binomial test works as expected (parameters num_bt, alpha_bt)
- Test if phases for generate rules/update rules/validation are run in the right moment (parameters num_steps_create_new_rules, num_upd_until_validation)

- [ ] Design testcases
- [ ] Approve testcases
- [ ] Write testcases

**Comment by dITySoftware** [comment]
@hoeldg is this issue still relevant or have you already fixed it?

**Comment by hoeldg** [comment]
Yes, the issue is still relevant
