### ISSUE TITLE
Exception when 29 Feb is parsed without year in a leap year and no log line occurs for more than one day

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#339]
In the situation stated in the title, the aminer reaches the line 
next_year_date_time = parsed_date_time.replace(self.start_year + 1)
However, if the last parsed time was Feb 29, the aminer checks if a year has passed already with that date and thereby triggers the following exception:

Traceback (most recent call last):
  File "/usr/bin/aminer", line 505, in <module>
    main()
  File "/usr/bin/aminer", line 261, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 138, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 262, in run_analysis
    current_stream_fd = log_stream.handle_stream()
  File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 360, in handle_stream
    self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 108, in consume_data
    match_element = self.parsing_model.get_match_element('', match_context)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/FirstMatchModelElement.py", line 41, in get_match_element
    child_match = child_element.get_match_element(current_path, match_context)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/SequenceModelElement.py", line 46, in get_match_element
    child_match = child_element.get_match_element(current_path, match_context)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py", line 255, in get_match_element
    next_year_date_time = parsed_date_time.replace(self.start_year + 1)
ValueError: day is out of range for month

To reproduce, use the following log file:
Feb 21 04:59:43 mail dovecot: imap(page): Logged out in=79 out=882
Feb 29 04:59:43 mail dovecot: imap(page): Logged out in=79 out=882
Mar  6 04:59:43 mail dovecot: imap(page): Logged out in=79 out=882
Mar 16 04:59:43 mail dovecot: imap(page): Logged out in=79 out=882

and any config, e.g.,:
config_properties = {}
config_properties['LogResourceList'] = [
        'file:///home/ubuntu/data/test2.txt',
        ]

config_properties['AMinerUser'] = 'aminer'
config_properties['AMinerGroup'] = 'aminer'

learn_mode = True
def build_analysis_pipeline(analysis_context):
    from aminer.parsing import DelimitedDataModelElement
    from aminer.parsing import FirstMatchModelElement
    from aminer.parsing import SequenceModelElement
    from aminer.parsing import DateTimeModelElement
    from aminer.parsing import FixedDataModelElement
    from aminer.parsing import AnyByteDataModelElement
    import AuditdParsingModel
    import ApacheAccessParsingModel
    import ApacheErrorParsingModel
    import EximParsingModel
    import SuricataFastParsingModel
    import SuricataEventParsingModel
    import SyslogParsingModel

    parsing_model = FirstMatchModelElement('parser', [
      AuditdParsingModel.get_model(),
      SuricataEventParsingModel.get_model(),
      SyslogParsingModel.get_model(),
      ApacheAccessParsingModel.get_model(),
      ApacheErrorParsingModel.get_model(),
      EximParsingModel.get_model(),
      SuricataFastParsingModel.get_model(),
    ])

    from aminer.analysis import AtomFilters
    atom_filter = AtomFilters.SubhandlerFilter(None)
    anomaly_event_handlers = []

    from aminer.input import SimpleByteStreamLineAtomizerFactory
    from aminer.input import SimpleMultisourceAtomSync
    analysis_context.atomizer_factory = SimpleByteStreamLineAtomizerFactory(
        parsing_model, [SimpleMultisourceAtomSync([atom_filter], sync_wait_time=5)], anomaly_event_handlers, default_timestamp_paths=['/parser/model/time',
    #parsing_model, [atom_filter], anomaly_event_handlers, default_timestamp_paths=['/parser/model/time',
          '/parser/model/type/execve/time',
          '/parser/model/type/proctitle/time',
          '/parser/model/type/syscall/time',
          '/parser/model/type/path/time',
          '/parser/model/type/login/time',
          '/parser/model/type/sockaddr/time',
          '/parser/model/type/unknown/time',
          '/parser/model/type/cred_refr/time',
          '/parser/model/type/user_start/time',
          '/parser/model/type/user_acct/time',
          '/parser/model/type/user_auth/time',
          '/parser/model/type/cred_disp/time',
          '/parser/model/type/service_start/time',
          '/parser/model/type/service_stop/time',
          '/parser/model/type/user_end/time',
          '/parser/model/type/cred_acq/time',
          '/parser/model/type/user_bprm_fcaps/time'])

    # Just report all unparsed atoms to the event handlers.
    from aminer.input import SimpleUnparsedAtomHandler
    atom_filter.add_handler(SimpleUnparsedAtomHandler(anomaly_event_handlers), stop_when_handled_flag=True)

    from aminer.analysis import ParserCount
    parserCount = ParserCount(analysis_context.aminer_config, [
        '/parser/model/type_str', # Audit
        '/parser/model/status_code', # Apache Access
        '/parser/model/php', # Apache Error
        '/parser/model/sp', # Exim
        '/parser/model/event_type_str', # Suricata Event
        '/parser/model/classification', # Suricata Fast
        '/parser/model/host', # Syslog
        ], report_interval=10, report_event_handlers=anomaly_event_handlers, reset_after_report_flag=True)
    analysis_context.register_component(parserCount, component_name='Parser Count')
    atom_filter.add_handler(parserCount)

    from aminer.analysis import NewMatchPathDetector
    new_match_path_detector = NewMatchPathDetector(analysis_context.aminer_config, anomaly_event_handlers, auto_include_flag=learn_mode)
    analysis_context.register_component(new_match_path_detector, component_name=None)
    atom_filter.add_handler(new_match_path_detector)

    # Add stdout stream printing for debugging, tuning.
    from aminer.events import StreamPrinterEventHandler
    anomaly_event_handlers.append(StreamPrinterEventHandler(analysis_context))

Update after new aminer version: I think the aminer is unable to parse logs from leap days when the year is missing, e.g.,
Feb 29 04:59:43 mail dovecot: imap(page): Logged out in=79 out=882

**Comment by dITySoftware** [comment]
I could reproduce the outputs using following config:

```python
from aminer.parsing.AnyByteDataModelElement import AnyByteDataModelElement
from aminer.parsing.DateTimeModelElement import DateTimeModelElement
from aminer.parsing.DecimalIntegerValueModelElement import DecimalIntegerValueModelElement
from aminer.parsing.DelimitedDataModelElement import DelimitedDataModelElement
from aminer.parsing.FirstMatchModelElement import FirstMatchModelElement
from aminer.parsing.FixedDataModelElement import FixedDataModelElement
from aminer.parsing.FixedWordlistDataModelElement import FixedWordlistDataModelElement
from aminer.parsing.IpAddressDataModelElement import IpAddressDataModelElement
from aminer.parsing.OptionalMatchModelElement import OptionalMatchModelElement
from aminer.parsing.SequenceModelElement import SequenceModelElement
from aminer.parsing.VariableByteDataModelElement import VariableByteDataModelElement
from aminer.parsing.RepeatedElementDataModelElement import RepeatedElementDataModelElement

config_properties = {}
config_properties['LogResourceList'] = [
'file:///tmp/syslog',
]

config_properties['Core.PersistenceDir'] = '/tmp/lib/aminer'
config_properties['Core.LogDir'] = '/tmp/lib/aminer/log'

config_properties['AminerUser'] = 'aminer'
config_properties['AminerGroup'] = 'aminer'

learn_mode = False
def build_analysis_pipeline(analysis_context):
	parsing_model = SequenceModelElement('model', [
        DateTimeModelElement('time', b'%b %d %H:%M:%S',start_year=2020),
        FixedDataModelElement('sp1', b' '),
        DelimitedDataModelElement('host', b' '),
        FirstMatchModelElement('service', [
            SequenceModelElement('dovecot', [
                FixedDataModelElement('dovecot_str', b' dovecot: '),
                FirstMatchModelElement('imap', [
                    SequenceModelElement('imap', [
                        FixedDataModelElement('imap_str', b'imap('),
                        DelimitedDataModelElement('user', b')'),
                        FixedDataModelElement('bracket_str', b'): '),
                        FirstMatchModelElement('message', [
                            SequenceModelElement('logout', [
                                FixedDataModelElement('logout_str', b'Logged out in='),
                                DecimalIntegerValueModelElement('in'),
                                FixedDataModelElement('out_str', b' out='),
                                DecimalIntegerValueModelElement('out')
                                ]),
                            SequenceModelElement('err_mail', [
                                FixedDataModelElement('mail_str', b'Error: Failed to autocreate mailbox INBOX: Internal error occurred. '
                                                      b'Refer to server log for more information. ['),
                                DelimitedDataModelElement('err_time', b']'),
                                FixedDataModelElement('brack', b']')
                                ]),
                            SequenceModelElement('err_open', [
                                FixedDataModelElement('err_str', b'Error: '),
                                DelimitedDataModelElement('function_name', b'('),
                                FixedDataModelElement('brack_str1', b'('),
                                DelimitedDataModelElement('arg', b')'),
                                FixedDataModelElement('failed_str', b') failed: Permission denied (euid='),
                                DecimalIntegerValueModelElement('euid'),
                                FixedDataModelElement('brack_str2', b'('),
                                DelimitedDataModelElement('euid_user', b')'),
                                FixedDataModelElement('egid_str', b') egid='),
                                DecimalIntegerValueModelElement('egid'),
                                FixedDataModelElement('brack_str3', b'('),
                                DelimitedDataModelElement('egid_user', b')'),
                                FixedDataModelElement('perm_str', b') missing +w perm: '),
                                DelimitedDataModelElement('mail_path', b','),
                                FixedDataModelElement('group_str', b', we\'re not in group '),
                                DecimalIntegerValueModelElement('group_id'),
                                FixedDataModelElement('brack_str4', b'('),
                                DelimitedDataModelElement('group_name', b')'),
                                FixedDataModelElement('owned_str', b'), dir owned by '),
                                DelimitedDataModelElement('owner', b' '),
                                FixedDataModelElement('mode_str', b' mode='),
                                DelimitedDataModelElement('mode', b')'),
                                FixedDataModelElement('brack_str5', b')'),
                                OptionalMatchModelElement(
                                    'set', SequenceModelElement('set', [
                                        FixedDataModelElement('set_str', b' (set'),
                                        DelimitedDataModelElement('param', b'='),
                                        FixedDataModelElement('equal_str', b'='),
                                        DelimitedDataModelElement('val', b')'),
                                        FixedDataModelElement('brack_str6', b')')
                                        ])
                                    )
                                ]),
                            SequenceModelElement('err_mail', [
                                FixedDataModelElement('mail_str', b'Failed to autocreate mailbox INBOX: Internal error occurred. '
                                                      b'Refer to server log for more information. ['),
                                DelimitedDataModelElement('err_time', b']'),
                                FixedDataModelElement('brack', b']')
                                ]),
                            ]),
                        ])])])])])

	from aminer.analysis import AtomFilters
	atom_filter = AtomFilters.SubhandlerFilter(None)
	anomaly_event_handlers = []

	from aminer.input.SimpleByteStreamLineAtomizerFactory import SimpleByteStreamLineAtomizerFactory
	from aminer.input.SimpleMultisourceAtomSync import SimpleMultisourceAtomSync
	analysis_context.atomizer_factory = SimpleByteStreamLineAtomizerFactory(
		parsing_model, [SimpleMultisourceAtomSync([atom_filter], sync_wait_time=5)], anomaly_event_handlers, default_timestamp_paths=['/parser/model/time'])

	# Just report all unparsed atoms to the event handlers.
	from aminer.input.SimpleUnparsedAtomHandler import SimpleUnparsedAtomHandler
	atom_filter.add_handler(SimpleUnparsedAtomHandler(anomaly_event_handlers), stop_when_handled_flag=True)

	from aminer.analysis.NewMatchPathDetector import NewMatchPathDetector
	new_match_path_detector = NewMatchPathDetector(analysis_context.aminer_config, anomaly_event_handlers, auto_include_flag=learn_mod
	analysis_context.register_component(new_match_path_detector, component_name=None)
	atom_filter.add_handler(new_match_path_detector)

	# Add stdout stream printing for debugging, tuning.
	from aminer.events.StreaPrinterEventHandler import StreamPrinterEventHandler
	anomaly_event_handlers.append(StreamPrinterEventHandler(analysis_context))
```

**Comment by dITySoftware** [comment]
Note that start_year is set to 2020, as this was a leap year.
the line
Feb 29 04:59:43 mail dovecot: imap(page): Logged out in=79 out=882
currently produces following error:
```
Traceback (most recent call last):
  File "/usr/bin/aminer", line 626, in <module>
    main()
  File "/usr/bin/aminer", line 370, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 81, in run_analysis_child
    child_return_status = child.run_analysis(3)
  File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 313, in run_analysis
    handle_result = fd_handler_object.handle_stream()
  File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 325, in handle_stream
    self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
  File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 158, in consume_data
    match_element = self.parsing_model.get_match_element('', match_context)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/SequenceModelElement.py", line 46, in get_match_element
    child_match = child_element.get_match_element(current_path, match_context)
  File "/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py", line 266, in get_match_element
    next_year_date_time = parsed_date_time.replace(self.start_year + 1)
ValueError: day is out of range for month
```
This happens, because max_time_jump_seconds is set to 86400 seconds.
Setting max_time_jump_seconds=86400*30 fixes this error.

**Comment by dITySoftware** [comment]
Using the above config all lines, but one, can be parsed.
`Mar 6 04:59:43 mail dovecot: imap(page): Logged out in=79 out=88`
%d does not support single digit days. This case is known and documented to fail. The current implementation supports formats defined in C89. https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
If we also want to support this case, we have to implement another parameter instead of %d.
