### ISSUE TITLE
Error adding MatchFilter via remotecontrol

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#344]
c 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 505, in <module>
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     main()
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 261, in main
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     run_analysis_child(aminer_config, program_name)
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer.py", line 138, in run_analysis_child
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     child_return_status = child.run_analysis(3)
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py", line 262, in run_analysis
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     current_stream_fd = log_stream.handle_stream()
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py", line 360, in handle_stream
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     self.last_consume_state = self.stream_atomizer.consume_data(self.log_data_resource.buffer, False)
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 62, in consume_data
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     if self.dispatch_atom(self.last_unconsumed_log_atom):
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py", line 133, in dispatch_atom
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     if handler.receive_atom(log_atom):
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/SimpleMultisourceAtomSync.py", line 115, in receive_atom
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     self.forward_atom(log_atom)
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer/input/SimpleMultisourceAtomSync.py", line 126, in forward_atom
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     handler.receive_atom(log_atom)
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer/analysis/AtomFilters.py", line 47, in receive_atom
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     handler_result = handler.receive_atom(log_atom)
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:   File "/usr/lib/logdata-anomaly-miner/aminer/analysis/MatchFilter.py", line 65, in receive_atom
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]:     listener.receive_event('Analysis.%s' % self.__class__.__name__, 'Log Atom Filtered',
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]: AttributeError: 'SimpleMultisourceAtomSync' object has no attribute 'receive_event'
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]: aminer.py: Analysis child process 27880 terminated unexpectedly with signal 0x100
Dec 09 11:31:05 mail.thermometer.com aminer.py[27757]: sys:1: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_UNIX, type=2050, proto=0>
Dec 09 11:31:06 mail.thermometer.com systemd[1]: aminer.service: Main process exited, code=exited, status=1/FAILURE
Dec 09 11:31:06 mail.thermometer.com systemd[1]: aminer.service: Unit entered failed state.
Dec 09 11:31:06 mail.thermometer.com systemd[1]: aminer.service: Failed with result 'exit-code'.
lines 917-1001/1001 (END)

**Comment by dITySoftware** [comment]
I do not know any details about this issue and no config in which this error happened, but obviously the SimpleMultisourceAtomSync is listed as an EventHandler, which is not the case.  Could it be that the SimpleMultisourceAtomSync was added to the AtomFilter? Is a Yaml or Python config used?

**Comment by dITySoftware** [comment]
Maybe when adding the component with the remote control the wrong. The command sent in the last mail was wrong. Right would be this one:
`add_handler_to_atom_filter_and_register_analysis_component(analysis_context, 'AtomFilter', MatchFilter(analysis_context.aminer_config, ['/parser/model/classification'], analysis_context.atomizer_factory.event_handler_list)`
