### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#383]
Since issue 372 was closed, I open a new issue for multiline support. See https://github.com/ait-aecid/logdata-anomaly-miner/issues/372

As I mentioned in the issue, it would be good to have an optional EOL parameter in the config to support simple multiline logs that are clearly separable, e.g., by \n\n that otherwise does not occur. We could also think about supporting more advanced multiline logs, in particular, json formatted logs where each json object spans over several lines rather than a single line. This could be solved by counting brackets, i.e., the ByteStreamAtomizer increases a counter (initially set to 0) for every "{" and decreases it for every "}" (or any other user-defined characters), and passes a log_atom to the parser every time this counter reaches 0.

**Comment by dITySoftware** [comment]
How should this EOL parameter work? If we implement the ByteStreamLineAtomizer to only pass log atoms if the seperator is found, for example \n\n, we cannot process normal one-liners.

The line end is search in this line:
line_end = stream_data.find(b'\n', consumed_length)

Basically we could check if
stream_data.find(eol_sep, consumed_length) != -1
and use that result or if it is -1 continue with the normal line end.

Also mechanisms to find overlong lines need to be disabled in that case.

Another drawback i can think of is that the multi-lines need to be written at one time, because if the stream is read before writing is finished, the separator will not be found. However i do not think this is that much of a deal..

As for the json support, we could implement another parameter which then uses an adapted version of the solution of this question: https://stackoverflow.com/questions/6886283/how-i-can-i-lazily-read-multiple-json-values-from-a-file-stream-in-python

**Comment by dITySoftware** [comment]
@landauermax  what do you think about that?

**Comment by landauermax** [comment]
Did you see how I solved it in my fork? Here: https://github.com/ait-aecid/logdata-anomaly-miner/compare/main...landauermax:feature_multiline

I agree that it is more difficult to implement when we have multiple source at the same time, and they have different EOLs. But we can leave that as an open issue for the future, for now it is only important and we assume that all logs files configured by the aminer have the same EOL. So when EOL='\n\n' is configured, we cannot process logs with the normal \n line end.

I dont think it is necessary to skip the overlong line detection, as long as the multi line logs do not have too many characters. I tested the fix in my fork and it worked.

It is not necessary that multi-lines are written at once, the aminer should wait until the EOL is found. This should already work in the current implementation.

The solution from stackoverflow works of course, but it seems to me that it will be horribly slow since each character is passed over many times, which is very critical since reading in the data should be as fast as possible. Feel free to try it out, but please compare the speed with the solution I proposed, because I think it will be much more efficient.

**Comment by dITySoftware** [comment]
Well in that case, why don't we just create a parameter, for example eol_separator, with the default value b'\n'? By overriding that parameter we could achieve the described functionality. You are right with the overlong lines as the max_line_length is also configureable. I did not see that.

According to my understanding the purpose of the aminer tool is to create structured data out of unstructered or semi-structured data. JSON is already a structured data type. There are other tools to work with JSON formatted data.
Personally i would not add this feature to the aminer as really no log file consists of JSON formatted data.

If you still think it is a good idea, I can create an new issue for this.
Maybe it would be better to not include it in the ByteStreamLineAtomizer, but rather create a new class (i.e. JsonStreamAtomizer).

**Comment by dITySoftware** [comment]
But I think my idea with trying to read multiple lines and if it fails to continue with single lines is much more practical.

**Comment by landauermax** [comment]
Having a parameter with default value '\n' that can be set in the configuration is exactly my suggestion.

Many logging frameworks support json output, for example, linux journal logging. We would not set it to json output if it was us to configure the logging, but in reality you have to work with whatever logs you receive from an organization, since it is unlikely that they change the configuration for you. While json is structured data, it contains unstructured data that we want to parse. E.g., {"message": <unstructured message>"}.

If you want to create a new class, please make sure that there is no duplicated code from the ByteStreamAtomizer.

I do not understand how it is possible to attempt reading in multiple lines and use single lines if that fails, because (i) the user would not expect that this happens and (ii) the parser is written for a specific log atom format that is either single or multiple line.

**Comment by dITySoftware** [comment]
Well a parser can normally parse different types of data. And the implementation would affect all parsers as it is in the ByteStreamLineAtomizer.

Ok, I will implement the JsonStreamAtomizer. I guess there will not be overlong lines and so on, so it will not be that much same code.

I will implement your proposed solution.

**Comment by dITySoftware** [comment]
What should happen in the JsonStreamAtomizer if a line does not contain any brackets or does not seem to be json? Should just be waited until a json occurs?

For example:
this is a log line.
data ={
    "message": "Hello"
    "secret": "world"
}
this is another log line.

My solution would be to just have one log atom, which sends all data until the closing bracket.  I would check if after the closing bracket is a \n and skip it in that case.

**Comment by landauermax** [comment]
This should rarely happen, since loggers configured for json are expected to only output valid json, and any non-json formatted text would not be considered valid. It is also unlikely that there is a "data = ", according to my experience json logs look like:
{"line": 1}
{"line": 2}
{"line": 3}

But we can agree that the text in between is also sent as its own log atom and let the parser handle it, e.g., report unparsed errors. So the atoms would be:
"this is a log line."
"{"message": "Hello", "secret": "world"}"
"this is another log line."

**Comment by dITySoftware** [comment]
Ok good to know. Should I then expect json logs to always be in one line? This is crucial as in that case the ByteStreamLineAtomizer can actually be used for this purpose.

**Comment by landauermax** [comment]
No, this was just a simplified example. Json logs can go over multiple lines, thats why I added it to this multiline issue, since it is a special form of multiline log.

**Comment by dITySoftware** [comment]
I guess i just got the idea you have. A combination of eol_sep and the json parameter could work. For example if eol_sep = '\n\n', then multiline json data would be possible, if an empty line follows. I guess that is the way to go instead of creating a new class for json.

**Comment by landauermax** [comment]
Unfortunately it is not that easy, since there is no empty line between two json objects. The way to find out when a json object ends is therefore to count the opening and closing curly braces that do not occur within strings, and "finish" a log atom as soon as the number of braces is equal, since then the json is complete.

For example,
{
"a": 1,
"b": {
"x": 2}
}

We start braceCount = 0 and with the first { set braceCount+=1, iterate over all characters until we find another { where we set braceCount += 1, then we keep iterating until we find } where we set braceCount-=1, then the final } where again we set braceCount-=1, at that point braceCount==0 and therefore we know that the log atom is complete.

**Comment by dITySoftware** [comment]
OK. Another question about the handling.
Assuming that normal strings also can contain brackets, it would be safer to only support json logs, where the first bracket is in a new line.

valid examples:
- here is a json: 
{"line": 1}
- here is a json: 
{
"a": 1,
"b": {
"x": 2}
}

Invalid examples:
- here is a json: {"line": 1}
- here is a json: {
"a": 1,
"b": {
"x": 2}
}

Or should the other case also be allowed? Then both examples examples would turn into the same following log atoms:
log atom 1: here is a json: 
log atom 2: {"line": 1}

log atom 1: here is a json: 
log atom 2: {
"a": 1,
"b": {
"x": 2}
}

Currently i am implementing the second option, so all prefixed strings are cut and sent out as an independent log atom.

**Comment by landauermax** [comment]
Yes, it should be fine to assume that the bracket is the first character in the line.
