### ISSUE TITLE
Reduce unit test dependencies

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#396]
I noticed that there are a lot of dependencies in the unit tests, e.g., checking whether tests fail or succeed depend on the output of the StreamPrinterEventHandler. This means that any changes in the StreamPrinterEventHandler can cause a lot of tests of other components to fail, which is strange for the unit tests and should be a matter of integration tests. In the unit tests, it would be good to use only the classes that are under test and create dummy objects for everything else. See https://stackoverflow.com/questions/2665812/what-is-mocking

**Comment by dITySoftware** [comment]
How else can i check if the output was triggered or not?
I need to know if a specific line triggers the anomaly handling. The return value does not say anything about that.

In the test cases I use a specific StreamPrinterEventHandler, which is targetted to a BytesIO object. Most of the time i check if the right output is triggered by specific data.

I understand the idea, however i do not know how to implement it. Are any changes to the StreamPrinterEventHandler planned?

**Comment by landauermax** [comment]
It is not about whether the text output is triggered, since the text output should be independent from the unit test. It is about the data stored in the detectors and the methods called by the detectors.

Have a look at the test that I created: https://github.com/ait-aecid/logdata-anomaly-miner/blob/development/aecid-testsuite/unit/analysis/EventSequenceDetectorTest.py

**Comment by dITySoftware** [comment]
Okay that is an good idea. However i would extract the dummy class, just like TestBase - maybe even into the same file. I will implement an prototype and we can change it if my ideas are not optimal.
