### ISSUE TITLE
Warning if two detectors persist on same file

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#398]
It is possible to define two detectors of the same type that will end up persisting in the same file - this can especially happen by accident, when the "Default" name is used. We should not prevent it completely, but at least print a warning when two or more detectors persist on the same file.

**Comment by whotwagner** [comment]
Instead of persisting into default-file use the unique-name of the analysis component as a filename unless the user specifies a name in the config

**Comment by dITySoftware** [comment]
How should the supposed code work? When the default persistence_id is used, an unique name should be generated. How should the unique name be loaded after restarting the aminer? The config file would have to be changed. This is very problematic.

We could use the id from PersistenceUtil.add_persistable_component. However if the order of the components is changed these also will be changed.

Another way would be to check if one component type is used more often (by checking the class name in AminerConfig.build_persistence_file_name. When the component exist more than once and the persistence_id is the same, an exception should be raised and aminer should be exited. This is my favorite solution.

**Comment by landauermax** [comment]
My suggestion would be to change the way we assign the unique ids (at the end of the component name, e.g., right now i think it is NewMatchPathValueDetector1, NewMatchPathValueComboDetector2, NewMatchPathValueDetector3, ... following the order in the config) to use a counter that is specific to each component, so when we have 2 value detectors and 1 combo detector in the config, the unique names would be NewMatchPathValueDetector1, NewMatchPathValueDetector2, NewMatchPathValueComboDetector1. In other words, each component type starts with a counter from 1 (or 0). In this case, if the combo detector is deleted from the config, the value detectors still have the correct unique name. Also the order should not be important for detectors of different types. 

Of course when deleting the first value detector, then the second value detector gets the id 1 instead; similarly, switching orders of the same detector types is problematic. In this cases, the user needs to specify a name manually, i do not think it is possible to find another workaround, but the solution I mentioned above should be good enough to cover most situations.

**Comment by dITySoftware** [comment]
Well currently the structure is component_name/Default/...
This works with only one detector per component type very well. I would just add a check if multiple components of the same type exist and if yes exit the program.

This seems to be the easiest and least intrusive way to guarantee working persistence.

**Comment by dITySoftware** [comment]
I will just create a pull request and you will see what i mean. If this does not work or needs changes we still can do them later on.

**Comment by landauermax** [comment]
I do not think it is component_name/Default/..., since Default is the name of the file. So it is component_name/Default.

Okay, but we definitely need to support more than one detector per component type. Otherwise we can only monitor a single value from all values in the log line, for example.

**Comment by dITySoftware** [comment]
In that case the user must configure different persistence_id's otherwise an exception is thrown.

**Comment by landauermax** [comment]
We just discussed this and decided that a warning should be sufficient if for one detector type more than one detectors exist without a persistence name. Something like: "<count> detectors of type <dtype> used without names. Please assign property persistence_id to avoid incorrect persistence loading."

The reason why we should not exit is that it is not the normal case to remove detectors and change their order in the config and this should not prevent people from using the aminer, since during development and testing the aminer is used with the clear flag most of the time anyway.

**Comment by dITySoftware** [comment]
ok i will implement it that way.
