### ISSUE TITLE
Pull request template confusing example

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#404]
The line "I added related issues using the "Fixes #123'-notations" in the pull request template is confusing, because Fixes#123 links to a closed issue. Better would be "I added related issues using the 'Fixes #`<issue-id>`'-notations".

Furthermore, the opening quote is a double quote and the closing a single.

**Comment by dITySoftware** [comment]
This is already fixed as the Fixes #123 was changed into Fixes .

**Comment by dITySoftware** [comment]
the opening and closing quote still do not match.
