### ISSUE TITLE
AMiner check4updates

### ISSUE THREAD

**Issue by skopikf** [ait-aecid/logdata-anomaly-miner#415]
Can we implement a cmd line flag, e.g., an extended --version flag or the like, that lets the AMiner check whether the latest version from github main is present on the system, e.g., querying tags on github and see if the own version string differs from the highest available version? This would let the user know if the latest version is installed without the need to manually check this on the webpage/github or debian package repo.

**Comment by whotwagner** [comment]
Yes, of course. I think that's a very good idea
