### ISSUE TITLE
check Linux distro before install/start

### ISSUE THREAD

**Issue by skopikf** [ait-aecid/logdata-anomaly-miner#416]
Do we have a mechanism that ensures AMiner ist installed/started on a Debian-based system? What happens if AMiner is executed on a non-debian system (need to test)? I suppose certain paths won't be available etc. Is there some check and meaningful error message? (e.g., when started on a Redhat-based system?)

**Comment by whotwagner** [comment]
We had support for RedHat in the aminer-ansible-role once. We did not update this part of the role after some work on the aminer. Issue #111 will solve this.
