### ISSUE TITLE
Fix tests for Getting Started

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#419]
The tests do not cover all configs of the "Getting Started" and "Try it out". They also do not cover changes of the aminer-commands. We need to parse those assets from the wiki-pages

**Comment by dITySoftware** [comment]
Please tell me if following procedures are sufficient for the pages:
Getting Started:

1. Search first yaml block and save it in <config-path>(first extract the config path from 2.)
2. search the next ``` after the first yaml block and run the 4th line after #
3. search the second yaml block and run it with the command found in 2.
4. search the fifth yaml block and run it with the command found in 2.

Try It Out:
I have noticed that the yaml config is just describing the template_config.yml.
Therefore i would check if the template_config.yml and hard fail if the yaml config parts are not contained in the template_config. I would even go the step, that the test should fail if the config does not match to 100% with the description. 

If the template_config.yml should not be the try-it-out.yml, then the text needs to be changed.

As the try-it-out config is summarized at the end of the wiki page, it would be easy to use that config and uncomment all analysis components. We would have to rely on the editors to correctly update the sub-parts of the config, as the test would be very complicated.

**Comment by whotwagner** [comment]
The tests should look like following:

1. parse the yaml-block with the config
2. parse the yaml-block with the command-line
3. run the parsed command-line with the parsed config
4. Search for specific words/phrases in the output to verify the success

**Comment by whotwagner** [comment]
Getting Started tests do not work as intended. What we wanted was:

1. parse the yaml-block with the config
2. parse the yaml-block with the command-line
3. run the parsed command-line with the parsed config
4. Search for specific words/phrases in the output to verify the success

In my opinion the last point is not implemented. That's why we did not see that we have major problems with the Getting Started now. The second scenario in the Getting Started does not print any anomalies because the paths have changed due to modifications of the ApacheAccessModel.

**Comment by dITySoftware** [comment]
The test currently just checks if the config is runable and does not check if the output matches the one in the wiki.
Also all other wiki-tests will have to be extended to check the outputs of all configurations.
