### ISSUE TITLE
Fix or remove dotimer()-test

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#448]
Every here and then the dotimer-test fails. It seems to be rather random to me. After starting a new test everything works as intended:

![image](https://user-images.githubusercontent.com/15659571/106887907-1e317100-66e6-11eb-854d-89004d70a066.png)

**Comment by dITySoftware** [comment]
This has nothing to do with the test case itself, rather it is affected by the email client you are using. Did this happen locally? I had these kind of issues and could solve it by changing the configurations.
