### ISSUE TITLE
Create standard configs for common log files

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#466]
We should create a folder containing some standard configs for log files that are common in practice, such as Apache Access logs and Audit logs. We have to make sure they work with all kinds of logging standards for these files, i.e., it may be necessary to also extend the parsers we have right now for the AIT-LDS. Also, we should only use detectors and configurations of detectors so that it is unlikely to get a high number of false positives. This should help others to get started more easily.

**Comment by ernstleierzopf** [comment]
I think this one is already done with the AIT-LDS2 configs. Please reopen if this is not the case.
