### ISSUE TITLE
Ubuntu-Tests fail with TypeErrors

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#470]
The Ubuntu-Tests fail with the following error:

```
Traceback (most recent call last):
  File "/usr/bin/aminer", line 606, in <module>
    main()
  File "/usr/bin/aminer", line 270, in main
    initialize_loggers(aminer_config, child_user_id, child_group_id)
  File "/usr/bin/aminer", line 102, in initialize_loggers
    persistence_dir_fd = SecureOSFunctions.secure_open_base_directory(persistence_dir_path)
  File "/usr/lib/logdata-anomaly-miner/aminer/util/SecureOSFunctions.py", line 37, in secure_open_base_directory
    if base_dir_path is None and (directory_name is None or not directory_name.startswith(b'/')):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

**Comment by whotwagner** [comment]
Those tests still fail:

```
/usr/bin/aminer:102: BytesWarning: Comparison between bytes and string
  if SecureOSFunctions.base_dir_path == AminerConfig.DEFAULT_PERSISTENCE_DIR:
Traceback (most recent call last):
  File "/usr/bin/aminer", line 605, in <module>
    main()
  File "/usr/bin/aminer", line 269, in main
    initialize_loggers(aminer_config, child_user_id, child_group_id)
  File "/usr/bin/aminer", line 130, in initialize_loggers
    log_dir_fd = SecureOSFunctions.secure_open_log_directory(log_dir, os.O_RDONLY | os.O_DIRECTORY | os.O_PATH)
  File "/usr/lib/logdata-anomaly-miner/aminer/util/SecureOSFunctions.py", line 91, in secure_open_log_directory
    log_dir_fd = os.open(log_directory_name, flags | os.O_NOFOLLOW | os.O_NOCTTY | os.O_DIRECTORY, dir_fd=base_dir_fd)
FileNotFoundError: [Errno 2] No such file or directory: b'/var/lib/aminer/log'

```

**Comment by dITySoftware** [comment]
Can you please tell me what directory was defined in 'Core.PersistenceDir' in your config? Was it '/var/lib/aminer' or some other location?

**Comment by whotwagner** [comment]
The configuration is parsed from the "Getting Started". See aecid-testsuite/docker/Dockerfile_deb:

```
RUN git clone -b $varbranch https://github.com/ait-aecid/logdata-anomaly-miner.wiki.git /opt/wiki
RUN awk '/^```yaml$/ && ++n == 1, /^```$/' < /opt/wiki/Getting-started-\(tutorial\).md | sed '/^```/ d' | sed '/^```python/ d' > /home/aminer/gettingStarted-config.yml
```

**Comment by dITySoftware** [comment]
Can reproduce the error with following lines
`sudo rm -r /var/lib/aminer
varbranch=development
git clone -b $varbranch https://github.com/ait-aecid/logdata-anomaly-miner.wiki.git /tmp/wiki
awk '/^```yaml$/ && ++n == 1, /^```$/' < /tmp/wiki/Getting-started-\(tutorial\).md | sed '/^```/ d' | sed '/^```python/ d' > /tmp/gettingStarted-config.yml
sudo aminer --config /tmp/gettingStarted-config.yml 
Unable to create log-directory: /var/lib/aminer/log
Unable to create log-directory: /var/lib/aminer/log
Traceback (most recent call last):
  File "/usr/bin/aminer", line 606, in <module>
    main()
  File "/usr/bin/aminer", line 269, in main
    initialize_loggers(aminer_config, child_user_id, child_group_id)
  File "/usr/bin/aminer", line 130, in initialize_loggers
    log_dir_fd = SecureOSFunctions.secure_open_log_directory(log_dir, os.O_RDONLY | os.O_DIRECTORY | os.O_PATH)
  File "/usr/lib/logdata-anomaly-miner/aminer/util/SecureOSFunctions.py", line 94, in secure_open_log_directory
    log_dir_fd = os.open(log_directory_name, flags | os.O_NOFOLLOW | os.O_NOCTTY | os.O_DIRECTORY)
FileNotFoundError: [Errno 2] No such file or directory: b'/var/lib/aminer/log'`

**Comment by dITySoftware** [comment]
Following commands fix the issue
```
sudo mkdir /var/lib/aminer
sudo chown aminer:aminer /var/lib/aminer
sudo aminer --config /tmp/gettingStarted-config.yml 
```
However another issue came up:
```
Traceback (most recent call last):
  File "/usr/bin/aminer", line 606, in <module>
    main()
  File "/usr/bin/aminer", line 269, in main
    initialize_loggers(aminer_config, child_user_id, child_group_id)
  File "/usr/bin/aminer", line 102, in initialize_loggers
    if SecureOSFunctions.base_dir_path == AminerConfig.DEFAULT_PERSISTENCE_DIR:
BytesWarning: Comparison between bytes and string
```
I will fix this one asap and create a new PR.

**Comment by dITySoftware** [comment]
Explanation:
The aminer is not responsible for creating the persistence directory. However it can be responsible for creating the log directory if default persistence parameters are used.
