### ISSUE TITLE
Timestamp of Detection

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#487]
We should differentiate between the timestamp of detection and the timestamp parsed from the log line. The timestamp of detection should always be available and be the real-time timestamp when the detector triggers the anomaly. The timestamp of the log line should only be available when it can be parsed from the log line.

**Comment by dITySoftware** [comment]
I do not know how to solve this issue? What classes should be checked? Should the LogAtom get a new parameter which defines the real-time/time of detection? Please suggest a possible solution and what classes should be changed for it.

**Comment by landauermax** [comment]
The timestamp of detection is not related to the log atom itself and it is therefore not necessary to add a new attribute. It should be as simple as adding event_data['DetectionTimestamp'] = time.time() in an appropriate place in the code, either in each detector when the anomalies are generated (which I would not prefer since this means a lot of duplicated code) or somewhere in the EventData or output components.

**Comment by dITySoftware** [comment]
Should this output also be available in text output mode or only in Json?
I think the right place would be the JsonConverterHandler.
Please approve that and i can add the code, as it should not be many changes.

**Comment by landauermax** [comment]
I think that having it in the json output is sufficient since we should try not to make the normal text output too overwhelming.
