### ISSUE TITLE
Improve error output for yaml config

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#497]
I used the learn_mode parameter from the ParserCount since I copied it from the Wiki of the main branch, but used the aminer of the development branch. The error I got is as follows: 

{'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 0': [{'allowlist_rules': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 1': [{'learn_mode': ['unknown field'], 'parsed_atom_handler_lookup_list': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 2': [{'learn_mode': ['unknown field'], 'parsed_atom_handler_dict': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 3': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 4': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 5': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 6': [{'id_path_list': ['required field'], 'report_interval': ['unknown field'] ...

It is not possible to see from this error that the learn_mode is the parameter that caused the aminer to fail. It would be good if the output would give a better indication on whats wrong.

**Comment by dITySoftware** [comment]
please post the full output. Maybe i can help.
I know it is a little confusing..

**Comment by landauermax** [comment]
root@user-0:/home/ubuntu/git/ares# aminer
{'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 0': [{'allowlist_rules': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 1': [{'learn_mode': ['unknown field'], 'parsed_atom_handler_lookup_list': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 2': [{'learn_mode': ['unknown field'], 'parsed_atom_handler_dict': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 3': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 4': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 5': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 6': [{'id_path_list': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 7': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 8': [{'bin_count': ['required field'], 'bin_size': ['required field'], 'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 9': [{'bin_count': ['required field'], 'bin_size': ['required field'], 'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'modulo_value': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'time_unit': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 10': [{'histogram_defs': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 11': [{'bin_definition': ['required field'], 'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 12': [{'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 13': [{'learn_mode': ['unknown field'], 'min_bin_elements': ['required field'], 'min_bin_time': ['required field'], 'report_interval': ['unknown field'], 'timestamp_path': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 14': [{'learn_mode': ['unknown field'], 'missing_value_string': ['required field'], 'report_interval': ['unknown field'], 'separator': ['required field'], 'stream': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 15': [{'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 16': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 17': [{'id_path_list': ['required field'], 'min_allowed_time_diff': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 18': [{'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 19': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 20': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 21': [{'learn_mode': ['unknown field']}], 'oneof definition 22': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'sub_rules': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 23': [{'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'rule_lookup_dict': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 24': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'sub_rule': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 25': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 26': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'value': ['required field']}], 'oneof definition 27': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'value_list': ['required field']}], 'oneof definition 28': [{'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'upper_limit': ['required field']}], 'oneof definition 29': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'regex': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 30': [{'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'seconds_modulo': ['required field'], 'type': ['unallowed value ParserCount'], 'upper_limit': ['required field']}], 'oneof definition 31': [{'learn_mode': ['unknown field'], 'limit_lookup_dict': ['required field'], 'path': ['required field'], 'report_interval': ['unknown field'], 'seconds_modulo': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 32': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 33': [{'learn_mode': ['unknown field'], 'parallel_check_count': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 34': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'ruleset': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 35': [{'learn_mode': ['unknown field'], 'max_time_delta': ['required field'], 'min_time_delta': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'rule_id': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 36': [{'action_id': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 37': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 38': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 39': [{'event_type_detector': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 40': [{'event_type_detector': ['required field'], 'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}]}]}]}
{'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 0': [{'allowlist_rules': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 1': [{'learn_mode': ['unknown field'], 'parsed_atom_handler_lookup_list': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 2': [{'learn_mode': ['unknown field'], 'parsed_atom_handler_dict': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 3': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 4': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 5': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 6': [{'id_path_list': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 7': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 8': [{'bin_count': ['required field'], 'bin_size': ['required field'], 'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 9': [{'bin_count': ['required field'], 'bin_size': ['required field'], 'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'modulo_value': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'time_unit': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 10': [{'histogram_defs': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 11': [{'bin_definition': ['required field'], 'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 12': [{'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 13': [{'learn_mode': ['unknown field'], 'min_bin_elements': ['required field'], 'min_bin_time': ['required field'], 'report_interval': ['unknown field'], 'timestamp_path': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 14': [{'learn_mode': ['unknown field'], 'missing_value_string': ['required field'], 'report_interval': ['unknown field'], 'separator': ['required field'], 'stream': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 15': [{'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 16': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 17': [{'id_path_list': ['required field'], 'min_allowed_time_diff': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 18': [{'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 19': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 20': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 21': [{'learn_mode': ['unknown field']}], 'oneof definition 22': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'sub_rules': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 23': [{'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'rule_lookup_dict': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 24': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'sub_rule': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 25': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 26': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'value': ['required field']}], 'oneof definition 27': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'value_list': ['required field']}], 'oneof definition 28': [{'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'upper_limit': ['required field']}], 'oneof definition 29': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'regex': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 30': [{'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'seconds_modulo': ['required field'], 'type': ['unallowed value ParserCount'], 'upper_limit': ['required field']}], 'oneof definition 31': [{'learn_mode': ['unknown field'], 'limit_lookup_dict': ['required field'], 'path': ['required field'], 'report_interval': ['unknown field'], 'seconds_modulo': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 32': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 33': [{'learn_mode': ['unknown field'], 'parallel_check_count': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 34': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'ruleset': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 35': [{'learn_mode': ['unknown field'], 'max_time_delta': ['required field'], 'min_time_delta': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'rule_id': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 36': [{'action_id': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 37': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 38': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 39': [{'event_type_detector': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 40': [{'event_type_detector': ['required field'], 'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}]}]}]}
Config-Error: {'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 0': [{'allowlist_rules': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 1': [{'learn_mode': ['unknown field'], 'parsed_atom_handler_lookup_list': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 2': [{'learn_mode': ['unknown field'], 'parsed_atom_handler_dict': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 3': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 4': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 5': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 6': [{'id_path_list': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 7': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 8': [{'bin_count': ['required field'], 'bin_size': ['required field'], 'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 9': [{'bin_count': ['required field'], 'bin_size': ['required field'], 'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'modulo_value': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'time_unit': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 10': [{'histogram_defs': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 11': [{'bin_definition': ['required field'], 'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 12': [{'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 13': [{'learn_mode': ['unknown field'], 'min_bin_elements': ['required field'], 'min_bin_time': ['required field'], 'report_interval': ['unknown field'], 'timestamp_path': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 14': [{'learn_mode': ['unknown field'], 'missing_value_string': ['required field'], 'report_interval': ['unknown field'], 'separator': ['required field'], 'stream': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 15': [{'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 16': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 17': [{'id_path_list': ['required field'], 'min_allowed_time_diff': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 18': [{'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 19': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 20': [{'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 21': [{'learn_mode': ['unknown field']}], 'oneof definition 22': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'sub_rules': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 23': [{'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'rule_lookup_dict': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 24': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'sub_rule': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 25': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 26': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'value': ['required field']}], 'oneof definition 27': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'value_list': ['required field']}], 'oneof definition 28': [{'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount'], 'upper_limit': ['required field']}], 'oneof definition 29': [{'learn_mode': ['unknown field'], 'path': ['required field'], 'paths': ['unknown field'], 'regex': ['required field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 30': [{'learn_mode': ['unknown field'], 'lower_limit': ['required field'], 'path': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'seconds_modulo': ['required field'], 'type': ['unallowed value ParserCount'], 'upper_limit': ['required field']}], 'oneof definition 31': [{'learn_mode': ['unknown field'], 'limit_lookup_dict': ['required field'], 'path': ['required field'], 'report_interval': ['unknown field'], 'seconds_modulo': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 32': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 33': [{'learn_mode': ['unknown field'], 'parallel_check_count': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 34': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'ruleset': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 35': [{'learn_mode': ['unknown field'], 'max_time_delta': ['required field'], 'min_time_delta': ['required field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'rule_id': ['required field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 36': [{'action_id': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 37': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 38': [{'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 39': [{'event_type_detector': ['required field'], 'learn_mode': ['unknown field'], 'paths': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}], 'oneof definition 40': [{'event_type_detector': ['required field'], 'learn_mode': ['unknown field'], 'report_interval': ['unknown field'], 'type': ['unallowed value ParserCount']}]}]}]}
root@user-0:/home/ubuntu/git/ares#

**Comment by landauermax** [comment]
But this issue is not about understanding this output, it is about improving the error output altogether.

**Comment by dITySoftware** [comment]
Ok i will look into it.

**Comment by dITySoftware** [comment]
I have improved the output in PR #501 and added a test for it. Could you please try it for yourself and confirm if the output is readable with the wiki TryItOut?

**Comment by landauermax** [comment]
I tried it and it is already much better now. I get this output for the same use case as above:

root@user-0:/home/ubuntu# aminer -C
{'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 21': [{'learn_mode': ['unknown field'], 'type': {'allowed': ['ParserCount']}}]}]}]}
{'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 21': [{'learn_mode': ['unknown field'], 'type': {'allowed': ['ParserCount']}}]}]}]}
Config-Error: {'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 21': [{'learn_mode': ['unknown field'], 'type': {'allowed': ['ParserCount']}}]}]}]}

But I wonder why the same information is printed three times? Could we avoid it and just print it once?

**Comment by dITySoftware** [comment]
> I tried it and it is already much better now. I get this output for the same use case as above:
> 
> root@user-0:/home/ubuntu# aminer -C
> {'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 21': [{'learn_mode': ['unknown field'], 'type': {'allowed': ['ParserCount']}}]}]}]}
> {'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 21': [{'learn_mode': ['unknown field'], 'type': {'allowed': ['ParserCount']}}]}]}]}
> Config-Error: {'Analysis': [{0: ['none or more than one rule validate', {'oneof definition 21': [{'learn_mode': ['unknown field'], 'type': {'allowed': ['ParserCount']}}]}]}]}
> 
> But I wonder why the same information is printed three times? Could we avoid it and just print it once?

Yes it is possible. I have updated the code now.
