### ISSUE TITLE
Adjust Detector-HowTo for code refactoring from development branch

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#512]
The HowTo currently only reflects the main branch, not the development branch.

Important changes so far:

- __init__.py in analysis does not exist anymore, it is not necessary to add new detectors there.
- The YAMLSchema file does not exist anymore. Instead, the parameter seq_len needs to be added to /home/ubuntu/aminer/source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.py 
- In addition, all parameters of the detector have to be added in /home/ubuntu/aminer/source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.py. This should look as follows (not verified):

                {
                    'id': {'type': 'string', 'nullable': True},
                    'type': {'type': 'string', 'allowed': ['SequenceDetector'], 'required': True},
                    'paths': {'type': 'list', 'schema': {'type': 'string'}, 'nullable': True},
                    'seq_len': {'type': 'integer', 'min': 1},
                    'persistence_id': {'type': 'string'},
                    'learn_mode': {'type': 'boolean'},
                    'output_logline': {'type': 'boolean'},
                    'output_event_handlers': {'type': 'list', 'nullable': True},
                },

- Also, AMiner should be Aminer in the config.

**Comment by dITySoftware** [comment]
AMinerConfig must be changed to AminerConfig
AMiner as a program has to be changed to aminer.
Also Parameters of the aminer should be checked. --Config is not valid any more for example.

**Comment by landauermax** [comment]
I fixed it, I did not see any AMiner program calls and incorrect parameters.
