### ISSUE TITLE
Fix Error output from JsonModelElement

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#516]
Currently the JsonModelElement prints the full line in shortest_unmatched_data. Maybe match_context.update(...) can help in updating the data.

**Comment by dITySoftware** [comment]
In the PR #520 I have added a fix for this issue. I tested it by using the json-input-demo-config.yml with the following line:
```
{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "Old", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```
Notice that "value": "Old" is not valid. The output is not perfect, because the Element is nested.
```
2021-03-06 11:00:30 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  Starting match update on b'{"menu": {\n  "id": "file",\n  "value": "File",\n  "popup": {\n    "menuitem": [\n      {"value": "Old", "onclick": "CreateNewDoc()"},\n      {"value": "Open", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
  Removed b'{"menu": {\n  "id": "file', remaining 217 bytes
  Removed b'",\n  "value": "File', remaining 198 bytes
  Removed b'",\n', remaining 195 bytes
  Shortest unmatched data was b'  "popup": {\n    "menuitem": [\n      {"value": "Old", "onclick": "CreateNewDoc()"},\n      {"value": "Open", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "Old", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```

Another example here:
```
{"menu": {
  "id": "file",
  "value": "File?",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```
Here the ? in value is not valid. It produces following output:
```
2021-03-06 11:09:35 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  Starting match update on b'{"menu": {\n  "id": "file",\n  "value": "File?",\n  "popup": {\n    "menuitem": [\n      {"value": "New", "onclick": "CreateNewDoc()"},\n      {"value": "Open", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
  Removed b'{"menu": {\n  "id": "file', remaining 218 bytes
  Removed b'",\n  ', remaining 213 bytes
  Shortest unmatched data was b'"value": "File?",\n  "popup": {\n    "menuitem": [\n      {"value": "New", "onclick": "CreateNewDoc()"},\n      {"value": "Open", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
{"menu": {
  "id": "file",
  "value": "File?",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```

**Comment by landauermax** [comment]
What happens when "Old" is not in the first key-value pair in the list, but in the second - is then the first unmatched data also "popup"? Like this:

{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "Open", "onclick": "CreateNewDoc()"},
      {"value": "Old", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}

Or when this does not occur in a list, but only a nested dict, does the match context updating then go in recursively and find out exactly at which value the matching failed? Like here, I would expect that "popup" and "menuitem" (including the list) and "valid_key" including "valid_value" is parsed, and only then comes the unmatched part:

{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "Open", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ],
    "test": {
      "valid_key": "valid_value"
      "invalid_key": "random_value"
  }
}}

The current changes are already an improvement, however, since nested dictionaries are very common in json log data, I think it would be good to enable this recursive view.

**Comment by dITySoftware** [comment]
> What happens when "Old" is not in the first key-value pair in the list, but in the second - is then the first unmatched data also "popup"? Like this:
> 
> ```
> {"menu": {
>   "id": "file",
>   "value": "File",
>   "popup": {
>     "menuitem": [
>       {"value": "Open", "onclick": "CreateNewDoc()"},
>       {"value": "Old", "onclick": "OpenDoc()"},
>       {"value": "Close", "onclick": "CloseDoc()"}
>     ]
>   }
> }}
> ```

No it does match the first key-value pair in the list. Concretely the output looks like this:
```
2021-03-08 11:09:05 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  Starting match update on b'{"menu": {\n  "id": "file",\n  "value": "File",\n  "popup": {\n    "menuitem": [\n      {"value": "Open", "onclick": "CreateNewDoc()"},\n      {"value": "Old", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
  Removed b'{"menu": {\n  "id": "file', remaining 217 bytes
  Removed b'",\n  "value": "File', remaining 198 bytes
  Removed b'",\n  "popup": {\n    "menuitem": [\n      {"value": "Open', remaining 143 bytes
  Removed b'", "onclick": "CreateNewDoc()', remaining 114 bytes
  Removed b'"},', remaining 111 bytes
  Shortest unmatched data was b'\n      {"value": "Old", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "Open", "onclick": "CreateNewDoc()"},
      {"value": "Old", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```

**Comment by dITySoftware** [comment]
> Or when this does not occur in a list, but only a nested dict, does the match context updating then go in recursively and find out exactly at which value the matching failed? Like here, I would expect that "popup" and "menuitem" (including the list) and "valid_key" including "valid_value" is parsed, and only then comes the unmatched part:
```
I guess i can also test this without adding the "test" key.
Here the data:
```
{"menu": {
  "id": "file",
  "value": "File",
  "invalid_key": True,
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```
Currently this does not work properly.

**Comment by dITySoftware** [comment]
> > Or when this does not occur in a list, but only a nested dict, does the match context updating then go in recursively and find out exactly at which value the matching failed? Like here, I would expect that "popup" and "menuitem" (including the list) and "valid_key" including "valid_value" is parsed, and only then comes the unmatched part:
> 
> I guess i can also test this without adding the "test" key.
> Here the data:
> 
> ```
> {"menu": {
>   "id": "file",
>   "value": "File",
>   "invalid_key": True,
>   "popup": {
>     "menuitem": [
>       {"value": "New", "onclick": "CreateNewDoc()"},
>       {"value": "Open", "onclick": "OpenDoc()"},
>       {"value": "Close", "onclick": "CloseDoc()"}
>     ]
>   }
> }}
> ```
> 
> Currently this does not work properly.

So this can not work, because the json has errors (True instead of true) and therefore the match_context is not updated.

**Comment by dITySoftware** [comment]
Updating the code I could produce following error output for the posted data:
```
2021-03-08 11:30:01 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  Starting match update on b'{"menu": {\n  "id": "file",\n  "value": "File",\n  "invalid_key": true,\n  "popup": {\n    "menuitem": [\n      {"value": "New", "onclick": "CreateNewDoc()"},\n      {"value": "Open", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
  Removed b'{"menu": {\n  "id": "file', remaining 240 bytes
  Removed b'",\n  "value": "File', remaining 221 bytes
  Removed b'",\n  "', remaining 215 bytes
  Shortest unmatched data was b'invalid_key": true,\n  "popup": {\n    "menuitem": [\n      {"value": "New", "onclick": "CreateNewDoc()"},\n      {"value": "Open", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
{"menu": {
  "id": "file",
  "value": "File",
  "invalid_key": true,
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```

**Comment by dITySoftware** [comment]
It is still problematic to output errors when a key is missing. Currently I have implemented it that the match context is updated until the point where the missing key should be placed. For example when removing the key 'value' in 'menu':
```
2021-03-08 11:52:45 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  Starting match update on b'{"menu": {\n  "id": "file",\n  "popup": {\n    "menuitem": [\n      {"value": "New", "onclick": "CreateNewDoc()"},\n      {"value": "Open", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
  Removed b'{"menu": {\n  "id": "file",\n  "popup": {\n    "menuitem": [\n      {"', remaining 156 bytes
  Shortest unmatched data was b'value": "New", "onclick": "CreateNewDoc()"},\n      {"value": "Open", "onclick": "OpenDoc()"},\n      {"value": "Close", "onclick": "CloseDoc()"}\n    ]\n  }\n}}'
{"menu": {
  "id": "file",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```

**Comment by landauermax** [comment]
Thanks, I think it looks already quite good. I think we can accept it at this stage and see over time how easy it is to work in practice or whether we need to make further adjustments.
