### ISSUE TITLE
HowTo Wiki: Remove or fix text about the __init__.py files

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#522]
The __init__.py files were removed. Please check the Wiki if this is considered.

**Comment by landauermax** [comment]
I did not see it anywhere in the wiki.

**Comment by dITySoftware** [comment]
> I did not see it anywhere in the wiki.

For example in https://github.com/ait-aecid/logdata-anomaly-miner/wiki/HowTo:-Create-your-own-SequenceDetector
You also have to make sure that the aminer is able to import the newly generated class. For this, open the following file for edit.
root@user-1:/home/ubuntu/aminer# vim /home/ubuntu/aminer/source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/__init__.py

**Comment by dITySoftware** [comment]
In https://github.com/ait-aecid/logdata-anomaly-miner/wiki/HowTo:-Create-your-own-SequenceDetector
seq_len already is defined in the AnalysisNormalisationSchema. This part can be deleted.

**Comment by landauermax** [comment]
This should only be present in the main version of the wiki, but I thought I fixed it in the development version.

**Comment by landauermax** [comment]
The seq_len is there, but i fixed the text. I cannot remove it completely, otherwise it is unclear how to add new parameters.

**Comment by dITySoftware** [comment]
ok, i will close this and open new issues if I find something.
