### ISSUE TITLE
Change persistence handling to standardize saving dictionaries as json in JsonUtil.encode_object

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/logdata-anomaly-miner#557]
For example like in the EFD:

for log_ev, freq in self.counts_prev.items():
  persist_data.append((log_ev, freq))

**Comment by dITySoftware** [comment]
Idea: use the old pull request to create a concept of persisting data and adapt it at a per class basis.

**Comment by dITySoftware** [comment]
Also change persistence after creating new unittests - wait before a major release.

**Comment by ernstleierzopf** [comment]
ToDo after unittests for the analysis classes are created - always also check the persisted data format on disk. These are breaking changes and need to be done before a new release.

**Comment by ernstleierzopf** [comment]
save ETD data as dictionary.

**Comment by ernstleierzopf** [comment]
#300 is related.

**Comment by ernstleierzopf** [comment]
I think there will never be a good opportunity to implement this this issue, because these would be breaking changes for existing deployments. There could be an automatic tool to update existing persisted data, but it might not be worth the implementation time and risks involved. The benefits simply do not outweight the risks and hassle.

@landauermax do you agree?

**Comment by landauermax** [comment]
Yes I agree, it is high risk and not worth it just for the sake of standardization.
