### ISSUE TITLE
Discuss: Rename all parser id's to element_id instead of path_id or anything else

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#587]
element_id fits for every parser and is better than having different names for the same attribute.

**Comment by dITySoftware** [comment]
Please comment on this issue if you think that this is not a valid point or if you want to approve this change.

**Comment by landauermax** [comment]
I agree.

**Comment by dITySoftware** [comment]
OK. Then I will implement this idea in the open PR #586.
