### ISSUE TITLE
Support aminer in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#607]
It would be convenient to run the aminer in the windows subsystem, because this would allow us to analyze windows logs without much problems (at least for quick demos). However, when I installed it, i got the following error:

landauerm@N3SIM1604:~$ sudo aminer --config /etc/aminer/config.yml
Traceback (most recent call last):
  File "/usr/bin/aminer", line 625, in <module>
    main()
  File "/usr/bin/aminer", line 369, in main
    run_analysis_child(aminer_config, program_name)
  File "/usr/bin/aminer", line 73, in run_analysis_child
    if posix1e.has_extended(persistence_dir_name):
OSError: [Errno 95] Operation not supported
aminer: Analysis child process 5284 terminated unexpectedly with signal 0x100

I do not know why this error occurs, but I would think that it should be possible to run the aminer in WSL. Maybe we need to replace some commands that are not valid in WSL? Please try to find a solution to this issue or at least provide information on why it is not possible or reasonable to run the aminer.

**Comment by dITySoftware** [comment]
The aminer is not supported in Windows. Please discuss if Windows support should be implemented with @whotwagner and @4cti0nfi9ure. When we want to support Windows we also have to setup a testing environment with a Windows installation.
