### ISSUE TITLE
Config Params not correctly imported in classes

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#624]
Similar to the bug discovered in #612 the values set by config params are not correctly transmitted to the classes due to incorrect imports. Example with param StatisticsLevel:

Set in config.yml:
`Log.StatisticsLevel: 2`

Added at the beginning of the receive_atom method in the NewMatchPathValueDetector:
```
print('static: ' + str(STAT_LEVEL))
print('dynamic: ' + str(AminerConfig.STAT_LEVEL))
```

Output:
```
static: 1
dynamic: 2
```

This can be solved by changing the imports from
`from aminer.AminerConfig import STAT_LEVEL, ...`

to 
`from aminer import AminerConfig`

and then use 
`AminerConfig.STAT_LEVEL`

This should be fixed for all parameters.

**Comment by dITySoftware** [comment]
I have found no other param than STAT_LEVEL to be affected.
