### ISSUE TITLE
Remove imports from init.py for better modularity

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#67]

**Comment by dITySoftware** [comment]
same as Issue #83 . This issue can be closed.

**Comment by 4cti0nfi9ure** [comment]
This is not the same as Issue #83. This one is about removing the imports in the init.py files.

**Comment by dITySoftware** [comment]
Hi, you can not remove the imports from init.py, otherwise the whole type checking with yaml does not work.

**Comment by dITySoftware** [comment]
> Hi, you can not remove the imports from init.py, otherwise the whole type checking with yaml does not work.

push.
