### ISSUE TITLE
Improve detector parameter consistency

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#703]
Many detectors require specific parameters that are specific to their detection approach. However, there are some general parameters that are shared by many detectors and I think make sense to standardize for all detectors. After a quick review I think that these are the following parameters:

- id
- type
- persistence_id
- suppress
- output_event_handlers
- ignore_list
- constraint_list
- output_logline
- learn_mode

Looking at the AnalysisValidationSchema, many detectors only have parts of these parameters implemented, e.g., the enhanced combo detector does not have constraint and ignore lists. Note that I would only do this for all detector components (that end with <...>Detector.py) and not for all analysis components, since they do not need all of these parameters; however, we could also find other sets of parameters that should be standardized for these groups, for example, for all <...>Rules.py. 

This would improve the overview in the aminer docs, since it would not be necessary to copy the same parameters over and over for each component.

**Comment by dITySoftware** [comment]
I will implement these changes always when I rewrite unittests for an analysis component. So do not move this issue, even when a pull request already is accepted.

**Comment by dITySoftware** [comment]
Also add the types to the parameters for the mypy static tests.

**Comment by dITySoftware** [comment]
auto_include_flag → learn_mode
output_log_lines → output_loglines

**Comment by dITySoftware** [comment]
TODO: also try to minimize code redundancy by using some kind of interface/superclass method for the typechecks in init methods.

**Comment by dITySoftware** [comment]
TODO VCD: move argument descriptions into method head.
