### ISSUE TITLE
Deactivate getting-Started tests

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#708]
Getting-Started tests do not work after changes in the wiki

**Comment by dITySoftware** [comment]
This may have only two reasons. The first one is when the structure of the wiki was changed - then the tests have to be adapted.
The second one is when the configs are not working any more (the intention of the test)

I think the test are important, even though they have to be updated continuously.

Please get back to me if the tests are not working and I will update them.
