### ISSUE TITLE
Support new timezone format

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#710]
The datetimemodel should be able to parse the timezone format +HH:MM, e.g., the following timestamp is used in windows event logs:

2021-04-22T11:11:21+02:00

**Comment by dITySoftware** [comment]
I think the : is problematic. Also is it valid to use +02:00 without UTC? I think the right form is UTC+02:00.

**Comment by landauermax** [comment]
The standard seems to be without UTC. I found an example here: https://www.loggly.com/wp-content/uploads/2016/11/Picture3.png or here https://www.loggly.com/ultimate-guide/net-searching-logs/
