### ISSUE TITLE
Empty element in json log

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#711]
Most elements, such as the FixedDataModelElement, do not allow empty strings. This makes sense in normal log data, however in json logs it can be that e.g. {"a": ""} which is as far as I know only possible to parse with a FixedWordlistElement, because it allows empty strings. 

I think we should introduce a parameter "allow_empty_data" that is false by default and integrate it into fixed data model element, fixed wordlist model element, anybyte element, and all others that may be affected.

**Comment by dITySoftware** [comment]
I don't think this is the right approach, as it only affects json data. Therefor it should be handled by the JsonModelElement.
I will implement a solution like the "ALLOW_ALL"-Keyword to solve this issue. For example it could be EMPTY, EMPTY_STRING or EMPTY_OBJECT. This also has to be documented in the JsonModelElement Class.

Please comment on this which identifier is preferred.

**Comment by landauermax** [comment]
I think it would be a good idea, but I do not understand how to apply it. Empty strings usually are not empty in every line, there could be a line {"a": ""} followed by {"a": "A"}. To reasonably parse this, one would require a VariableByte or Wordlist element that allows empty data, since setting EMPTY_STRING alone does not allow to specify whether all other strings that can occur in this position are from a list or a certain alphabet, etc.

**Comment by dITySoftware** [comment]
Well in that case it is possible to use a VariableByteDataME or whatever within an OptionalMatchElement. Only the special case where the string always is empty should be handled with EMPTY_STRING.

**Comment by landauermax** [comment]
Ok, I was not aware that this is possible. I think then your suggestion is fine.
