### ISSUE TITLE
FileWriterHandler

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#801]
An Eventhandler that writes the AMiner's output to a file.

**Comment by dITySoftware** [comment]
The StreamPrinterEventHandler can already do that. In the python configs this should be no issue as an output stream can be opened easily. In yaml configs this functionality is already implemented with the 'output_file_path' parameter (StreamPrinterEventHandler). 

Please reopen this issue if this is no viable solution.
