### ISSUE TITLE
Create docker compose configuration for aecid-tools 

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#807]
Create a docker compose file for:

- logdata-anomaly-miner
- aminer-aelastic
- aminer-akafka

**Comment by prajeshpradhan** [comment]
If its only to create docker compose i would like to contribute.

**Comment by whotwagner** [comment]
Hi, I would appreciate it very much if you would help us with this. There are some fallsteps:

- We don't have a dockerfile for aminer-aelastic and aminer-akafka( yet)
- We don't have images for aelastic and akafka in our docker-hub( yet)
- logdata-anomaly-miner and aminer-aelastic(and aminer-akafka) communicate via unix-domain-sockets. Therefore we have to ensure that they use the same volume with the same permissions.

We could split the work if you want. You create a simple Docker-Compose-File for logdata-anomaly-miner without aminer-akafka and aminer-aelastic(so you don't have to worry about the unix-domain-sockets and their permissions) and I take care of all the rest.

You can find documentation about how to use logdata-anomaly-miner with docker here: https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Deployment-with-Docker

Please make sure that we have the necessary mountpoints in volumes.
