### ISSUE TITLE
YamlConfig: open-function in StreamPrinterEventHandler without a proper close()

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#816]
In line 757 of YamlConfig.py there is a open() function without a proper close(). We can fix that by using a "with open" directive

**Comment by dITySoftware** [comment]
Well if we close the stream the StreamPrinterEventHandler can not write anything after the config was loaded. The stream must stay open.

We also do not close sys.stdout when shutting down the aminer (default value of the StreamPrinterEventHandler)

**Comment by whotwagner** [comment]
I mentioned the "with open(name, 'w+') as f" so that we ensure that python will automatically close the filedescriptor outside the context. I believe that a open() without any consideration of a close() is bad practice

**Comment by dITySoftware** [comment]
Yes open() without close() is bad practice. However using "with open(name, 'w+') as f" will close the file handler as soon as it gets out of context, which is right after the with block is finished.

If we want to achieve the behavior, we would have to add a check right after the analysis loop was left - see AnalysisChild.py - line 434ff (development branch). There we would have to loop through all event handlers by extracting the list from self.analysis_context.atomizer_factory.atom_handler_list and check if the event handler is a StreamPrinterEventHandler and if the stream is not sys.stdout - we do not want to close sys.stdout i guess.

Should I add this check?

**Comment by whotwagner** [comment]
I am going to sleep over that problem. Because it's a little bit more complex. If we never close the filehandle, tools like logrotate will never have the opportunity to rotate the file properly. I rescheduled this issue. It's not for the next milestone anymore.

**Comment by dITySoftware** [comment]
This issue is the same as #833.

I have thought about this problem. What if we define a parameter "buffer_size"=1.048.576 (1MB) and add a check after flushing in the StreamPrinterEventHandler. When the written size is bigger than buffer_size, we simply close the file and immediately reopen it.
I have read up about the logrotate tool and if I understand it correctly, it simply renames/moves the file and creates a new file. The problem is that the file handle then points to the old file, which has been moved. To fix this problem the file needs to be reopened.
However we could also simply reopen the file handler after every time writing to the StreamPrinterEventHandler. This is highly inefficient.

For the logging tools there is a great solution, which does not need the use of external tools. It is the [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler). We could introduce new config parameters for the size after which the file is rotated and the number of rotation files. Both defaulting to zero, which means no rotations. We could also set the number of rotation files to a default of 10 if the size parameter is set.

**Comment by dITySoftware** [comment]
Also when leaving the Analysis loop, we should close the stream of StreamPrinter, if it is not the default stdout.

**Comment by whotwagner** [comment]
Another more generic solution would be to send a message/signal via aminer-remote-control. "reopen-outputfilehandles". Logrotate could simply send the command after rotating the logfile

**Comment by dITySoftware** [comment]
I have also read about this solution here: https://stackoverflow.com/questions/53188731/logging-compatibly-with-logrotate/53201067#53201067
We would have to use another signal than SIGHUP, as this one is already used by the aminer.

I will have to check if logging.getLogger(DEBUG_LOG_NAME).handlers returns a reference to the handlers list in the log_rotation_handler. If this works, there should not be any problem.

Is this the preferred solution?

And do we need some automated tests with logrotate or is it enough if manual tests work? I think we do not need them..

**Comment by whotwagner** [comment]
I don't think that we need signals because we can use the aminer-remotecontrol to set a variable that signalizes the aminer to reopen the output filehandlers as soon as possible.

I think we should use different variables to reopen the logfiles of aminer and to reopen the output filehandlers

I don't think it is necessary to test the logrotation, but we should  write integration tests that proof that the filehanders are reopened properly.

**Comment by dITySoftware** [comment]
That's also possible.
Should we reopen all files, including the ones from the StreamPrinterEventHandler?

What do you think of shutting down logging completely and re-initializing it like in the beginning of the program? I think this is less error-prone than messing around with the open handlers.
We would have to move the initialize_loggers method to AnalysisChild and import it within aminer.py to prevent import errors.

**Comment by dITySoftware** [comment]
forgot to add the source of this idea:
https://stackoverflow.com/a/12034791

**Comment by whotwagner** [comment]
I close this issue and reopen different issues that target logfiles and streamprinter. See #833 and #990

**Comment by whotwagner** [comment]
The problem with open filehandler and the StreamPrinterEventHandler still exists ![image](https://user-images.githubusercontent.com/15659571/158817428-e386c48c-1f3f-4f3c-8d5c-d70b19ec370b.png)

**Comment by whotwagner** [comment]
The problem with the open filehandler in the StreamPrinterEventHandler still exists ![image](https://user-images.githubusercontent.com/15659571/158818119-e527c3d1-91ca-4c2c-b24d-85903bba1b2c.png)

**Comment by dITySoftware** [comment]
I cannot reproduce the issue. Is it reproducable for you?
If yes, could you send me the config and logs used to reproduce?

Could it have something to do with permissions of the file? Was the file maybe deleted before aminer could close it?

**Comment by ernstleierzopf** [comment]
ping @whotwagner

**Comment by whotwagner** [comment]
I'll try to reproduce it. Hold on...

**Comment by whotwagner** [comment]
I wasn't able to reproduce and assume that it's fixed already.
