### ISSUE TITLE
ApacheErrorParsingModel does not cover all paths.

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#819]
Various log lines can not be parsed with the parser model. The "error_str" is problematic, as the error most often is not [:error]. I could not find any log line only having [:error].

Instead of "error_str" i would add a "sp3" with b"] [", a DelimitedModelElement which also consumes the delimiter with b"]" as delimiter and a FixedDataME "pid_str" with b" [pid "

Example log lines I found are:
```
cat /var/log/apache2/error.log.1
[Mon May 04 18:20:28.595169 2020] [ssl:warn] [pid 7526] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Mon May 04 18:20:28.595411 2020] [ssl:error] [pid 7526] AH02218: ssl_stapling_init_cert: no OCSP URI in certificate and no SSLStaplingForceURL set [subject: emailAddress=sample@sample.at,CN=Name,OU=who,O=O,L=where,ST=country,C=AT / issuer: emailAddress=s1910304008@students.fh-hagenberg.at,CN=CN CA,OU=OU,O=O,L=where,ST=AT,C=AT / serial: 2494FC36B810A76AB242E4E374BE635AD965C346 / notbefore: Nov 16 16:08:42 2019 GMT / notafter: Feb 14 16:08:42 2020 GMT]
[Mon May 04 18:20:28.595423 2020] [ssl:error] [pid 7526] AH02604: Unable to configure certificate localhost:443:0 for stapling
[Mon May 04 18:20:28.595514 2020] [mpm_prefork:notice] [pid 7526] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Mon May 04 18:20:28.595521 2020] [core:notice] [pid 7526] AH00094: Command line: '/usr/sbin/apache2'
[Mon May 04 18:32:03.411414 2020] [mpm_prefork:notice] [pid 7526] AH00169: caught SIGTERM, shutting down

[Fri Sep 09 10:42:29.902022 2011] [core:error] [pid 35708:tid 4328636416] [client 72.15.99.187] File does not exist: /usr/local/apache2/htdocs/favicon.ico
```

**Comment by dITySoftware** [comment]
@landauermax please comment on this. Should we allow other data too? for example core:notice? Those are also in the error logs

**Comment by dITySoftware** [comment]
Also it seems that "[client " is not in every log line.
"] PHP " also is no must in these log lines.

This parser model is not working for the most data i found. Should I try to extend the parser and find even more data to test it with?

**Comment by dITySoftware** [comment]
If this parser model is only intended to be used for internal data, please post some anonymized data for testing.

**Comment by landauermax** [comment]
The parsers in the ait-lds folder are not designed to work with general data (otherwise they would be in the generic folder). They are meant to work for the AIT-LDSv1.1 (only some attack lines cannot be parsed, but that is fine since they are not part of the normal behavior and therefore correctly yield unparsed anomalies). You can download the dataset and collect samples for all parsers from the official data repository: https://zenodo.org/record/4264796#.YPFr9UxCRhE

**Comment by dITySoftware** [comment]
Thanks that was exactly what I was searching for!
