### ISSUE TITLE
AuditdParsingModel can not parse CWD

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#821]
Following line can not be parsed with the parsing model. Should it be extended?
`type=CWD msg=audit(1522927552.749:917):  cwd="/root"`

**Comment by landauermax** [comment]
I think the AIT-LDS does not involve this event, therefore it is not necessary. The generic parser for audit logs (generic/AudispdParsingModel.py) should cover this type of events - if not, then that parser needs to be extended.

**Comment by dITySoftware** [comment]
Okay, thanks - closing..
