### ISSUE TITLE
SuricataEventParsingModel: parser model parses json data. For this use case the JsonModelElement would be better fitting.

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#823]
@landauermax should we refactor this config or just leave it as is?

**Comment by dITySoftware** [comment]
Another question: should we generally change parser models which parse json data?

**Comment by landauermax** [comment]
No it is not necessary, since this parser is just for the AIT-LDS and it works for that data. We already published some try-it-outs with this parser and they would not work anymore if the paths change. It is sufficient to only change the generic parsers.

**Comment by landauermax** [comment]
Are there any parsers outside of the ait-lds directory that involve json and do not use the JsonParsingModel?

**Comment by dITySoftware** [comment]
No, the generic parsers do not involve any json data. Closing..
