### ISSUE TITLE
Make sure that docs/conf.py uses the same aminer-release than the metadata.py

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#824]
The aminer-version-string in docs/conf.py must be the same as in source/root/usr/lib/logdata-anomaly-miner/metadata.py

**Comment by dITySoftware** [comment]
I have just came upon this while looking at other issues. Should there be a simple automated test for this? Also looking at the metadata.py, we should add @hoeldg to the authors list. If you want me to do this, please reassign the task.

**Comment by whotwagner** [comment]
Yes we really have to add hoeldg to the authors list. No I don't think of a test. More of a helper-script to set/increase the versions-string in both files.
