### ISSUE TITLE
Parameters for analysis components to switch to detection mode

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#831]
Changing the learn_mode of the aminer requires a restart or waiting until a certain amount of time has passed, which is not convenient. There was therefore a request to be able to set in the config after how much time the learn_mode should be automatically changed from True to False. E.g., switch_learn_mode_false_time = 3600 will cause that the detector changes its learn_mode automatically after 3600 seconds (based on log data timestamps).

In addition, it should also be possible to change the learn_mode after no anomalies were reported for a certain amount of time. E.g., switch_learn_mode_false_anomaly_time = 3600 means that when no anomalies are produced by this detector for 3600 seconds, the learn mode changes.

**Comment by dITySoftware** [comment]
As I understand this request, the switch_learn_mode_false_anomaly_time parameter should be a global one and all analysis components should switch after that time. Is this right?

I think it is hard to determine how long no anomaly was produced from inside of an analysis component.

**Comment by landauermax** [comment]
Both parameters should be set for specific analysis components. (Well, we can make both parameters also global but then allow each specific detector to overwrite the global values, same as it is currently possible with the learn_mode).

What is the problem in determining that? It is just about storing the timestamp of the most recent log line that caused an anomaly.

**Comment by dITySoftware** [comment]
Yeah, that will work. I thought about the problem that receive_atom is only called, when an atom occurs. But we can just add a check in the beginning when the next atom comes.
