### ISSUE TITLE
Remove or fix cpu limit configuration

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#85]

**Comment by dITySoftware** [comment]
What is the Problem of this feature? The value is first converted into Integer by using the int() method. Can malicious code be inserted?

When changing he property, the input is validated with the shlex.quote method.

**Comment by whotwagner** [comment]
The problems are following:

1. we use dpkg to install cpulimit. this code won't work with other platforms than debian-based linux
2. we use cpulimit, so this code is not very portable in terms of: it only works with linux

**Comment by dITySoftware** [comment]
should i solve those issues or should i remove the functionality?
The second issue can be solved by not enabling the functionality for non linux systems.

**Comment by whotwagner** [comment]
I would rather discuss different approaches before. Like:

1. Do we really need this functionality
2. Do we find a portable "python-way" solution
3. Or do we find a non-portable solution that could easily modified for other platforms

**Comment by dITySoftware** [comment]
I can not answer the first question. If you say we don't need it, I can delete the functionality. However it can be useful to test the stability of the aminer on devices with low ressources (i. e. low RAM). The problematic cpulimit is not as useful as the Memory parameter and can be deleted. If the functionality is needed, it can also be just run in the commandline. It's a one-liner
cpulimit -p <pid> -l <cpu-usage-in-percent>.

2. There is no easy way to implement this feature..
3. Same as 2

Should i remove cpulimit?

**Comment by whotwagner** [comment]
I will discuss that tomorrow with @4cti0nfi9ure and @landauermax

**Comment by whotwagner** [comment]
Yes, remove cpulimit and it's configuration-parameters

**Comment by dITySoftware** [comment]
however the RAM parameter stays?

**Comment by whotwagner** [comment]
Do we still need it?

**Comment by dITySoftware** [comment]
it can be useful for simulating purposes. Also it is implemented in a pythonic, portable way.

**Comment by whotwagner** [comment]
Then let's keep it

**Comment by dITySoftware** [comment]
Fixed in PR #217
