### ISSUE TITLE
Add parsed log JSON output for VerboseUnparsedAtomHandler

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#86]

**Comment by dITySoftware** [comment]
There is an JSON output for the VerboseUnparsedAtomHandler. Here is an example from the AMiner demo:

2020-09-23 10:43:53 Unparsed atom received
VerboseUnparsedAtomHandler: "VerboseUnparsedHandler" (1 lines)
  {
  "DebugLog": [
    "Starting match update on b'2020-09-23 10:43:52 localhost root cron[123]: Job `cron.daily`'",
    "Removed b'2020-09-23 10:43:52', remaining 43 bytes",
    "Removed b' ', remaining 42 bytes",
    "Removed b'localhost', remaining 33 bytes",
    "Starting match update on b'2020-09-23 10:43:52 localhost root cron[123]: Job `cron.daily`'",
    "Removed b'2020-09-23 10:43:52', remaining 43 bytes",
    "Removed b' ', remaining 42 bytes",
    "Removed b'localhost', remaining 33 bytes",
    "Starting match update on b'2020-09-23 10:43:52 localhost root cron[123]: Job `cron.daily`'",
    "Removed b'2020-09-23 10:43:52', remaining 43 bytes",
    "Removed b' ', remaining 42 bytes",
    "Removed b'localhost', remaining 33 bytes",
    "Removed b' ', remaining 32 bytes",
    "Removed b'root', remaining 28 bytes",
    "Removed b' cron[', remaining 22 bytes",
    "Removed b'123', remaining 19 bytes",
    "Starting match update on b'2020-09-23 10:43:52 localhost root cron[123]: Job `cron.daily`'",
    "Removed b'2020', remaining 58 bytes",
    "Shortest unmatched data was b']: Job `cron.daily`'",
    ""
  ],
  "LogData": {
    "RawLogData": [
      "2020-09-23 10:43:52 localhost root cron[123]: Job `cron.daily`"
    ],
    "Timestamps": [
      1600850633.16
    ],
    "LogLinesCount": 1
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": 2,
    "AnalysisComponentType": "VerboseUnparsedAtomHandler",
    "AnalysisComponentName": "VerboseUnparsedHandler",
    "Message": "Unparsed atom received",
    "PersistenceFileName": null
  }
}

This issue can be closed.
