### ISSUE TITLE
JsonModelElement: Unfitting log lines are parsed, when the parser includes arrays

### ISSUE THREAD

**Issue by hoeldg** [ait-aecid/logdata-anomaly-miner#882]
The following example shows a parser and log lines. The Parser should parse the first two but not the last two.
At the moment, all log lines are parsed.

Parser:
        - id: a_var0
          type: VariableByteDataModelElement
          name: 'a_var0'
          args: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"

        - id: json
          start: True
          type: JsonModelElement
          name: 'model'
          optional_key_prefix: '_'
          key_parser_dict:
            a:
              - a_var0

Log lines:
{"a": ["b2"]}
{"a": [[[[[[[[[[[[[["b1"]]]]]]]]]]]]]]}
{"a": "b2"}
{"a": []}

**Comment by dITySoftware** [comment]
The fourth example actually is a valid one, because the array can also be empty. The third one is fixed now.
