### ISSUE TITLE
get_time_trigger_class always returns one of two static values, which are always same for an analyser.

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#886]
Better create an class attribute (for example "time_trigger_class") and set it in the init method.
The get_time_trigger_class then can be implemented in the interface as a method.

**Comment by landauermax** [comment]
I think the purpose of the interface method is that it enforces that the method must be defined in the detectors. If we change this to a variable then it is not guaranteed that it is overwritten when implementing a detector. Would there be any other advantage?

**Comment by dITySoftware** [comment]
I have not thought about this. However there seems to also be a solution for this according to this STO post: https://stackoverflow.com/questions/2736255/abstract-attributes-in-python/38732834

It would save many lines of code. Also are you sure that every component has the correct setting for the time trigger class?

**Comment by landauermax** [comment]
Yes, this should be a valid solution. I am not sure that the current settings are correct in every component, but I never experienced any problems that were caused by the time trigger class in the past.
