### ISSUE TITLE
Add class diagramm and process flow diagramm to documentation

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#89]

**Comment by dITySoftware** [comment]
what software is preferrably to be used?

**Comment by dITySoftware** [comment]
where should these diagrams be saved?

**Comment by landauermax** [comment]
I have already created a class diagram and process flow diagram some years ago - see attached files. I am sure they are not up to date anymore and need to be adapted and extended for new functionality. They should be placed in the aminer docs, maybe in a new directory or split up into aminer and remote control diagrams: https://github.com/ait-aecid/logdata-anomaly-miner/tree/master/source/root/usr/share/doc/logdata-anomaly-miner
[Diagrams.zip](https://github.com/ait-aecid/logdata-anomaly-miner/files/5517168/Diagrams.zip)

**Comment by dITySoftware** [comment]
In the current diagram only NewMatchPathValueComboDetector and NewMatchPathDetector were added. Should no other analysis component be added there?

**Comment by landauermax** [comment]
I think it is necessary and reasonable to abstract over analysis components, otherwise the diagram becomes way too large. So maybe just use one representative class for all detectors. Same for parsing model elements.
