### ISSUE TITLE
Verbose debug output parameter

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#91]

**Comment by dITySoftware** [comment]
Probably the same as Issue #149. Please close this issue as the other one is newer.

**Comment by landauermax** [comment]
I do not think it is exactly the same. The stat file just provides a kind of log file for the AMiner that is always useful for keeping a record of what is going on, whilte the debug output gives you a lot more information that is only used when debugging.

**Comment by dITySoftware** [comment]
Should the debug parameter be implemented per analysis component or globally?

**Comment by landauermax** [comment]
The debug parameter is used globally when calling the AMiner on the command line and has different levels. Debug logs are produced by all components, not just eh analysis components. However, it should also be possible to override the global debug parameter in the config for all classes that implement debug output.

**Comment by dITySoftware** [comment]
I have now googled some ways of logging debug messages and their verbosity. Basically it is differentiated between linux kernel logs and program logs.

Here are some log verbosity levels defined:
https://verboselogs.readthedocs.io/en/latest/readme.html

Here is an good example of how verbosity levels can be implemented:
https://symfony.com/doc/current/console/verbosity.html

It is written in PHP, but the idea stays the same.  There are five different log levels.
-  -q or --quite: remove all unnessecary log messages
- None (Default): printing all above and inclusive level 30 Warning
- v: print level 20 Info and above
- vv print level 15 verbose and above
- vvv print all levels

syslog provides following log levels, but I think they are not applicable for the aminer:
0 - Emergency (emerg)
1 - Alerts (alert)
2 - Critical (crit)
3 - Errors (err)
4 - Warnings (warn)
5 - Notification (notice)
6 - Information (info)
7 - Debug (debug) 

Should i implement the suggested solution?

**Comment by dITySoftware** [comment]
classifying the log messages into the right log level is another issue that needs to be addressed. I could provide an implementation and correct the levels when the PR is reviewed.

**Comment by dITySoftware** [comment]
as statistics also need different levels, i would implement this parameter in the aminer by using
--debug -v for example and --stat -v.

Both parameters should also have an abbreviation and support numeric values from -1 to 3 to be easier to use.

I would not recommend implementing debug and stat parameters for every single component of the aminer. It would be more confusing for the user and harder to maintain for us. Log files and statistic files are normally not viewed every day and should provide information in the case of some error. Therefor it could be useful to have the full history of events logged.

**Comment by landauermax** [comment]
I think it is not standard to make two consecutive parameters such as --debug -v, at least I have never used such a feature. I would prefer to have --debug or -d for debug output, where the level is set by either a number, e.g., -d 3 for level 3, or by -ddd for level 3. We can change the stat verbosity using another parameter, e.g., --stat 3 or -sss. Also, the values should not start at -1 but rather at 0, because when setting -1 it easy to mix up the dash with the dash of the parameters.

I agree that we should not clutter the code with debug and stat output. The commands should definitely not take up more than one line, so we should define a global function debug_output('<message>') that checks the log level and acts accordingly, instead of checking the log level every time we want to output something. Logging is not necessary for every component, but for sure for all the detectors, because this is where the errors occur.

**Comment by dITySoftware** [comment]
I agree with --debug 3 or -d 3 or -ddd.

For debug i would use 0-4, default 1 and for stat i would use 0-2, default 1. 0 means no statistics output.
I would add the function debug_output() and stat_output() in PersistencyUtil and the according global variables DEBUG_LEVEL and STAT_LEVEL in AMinerConfig.

The logging module defines strings for the different logging levels like logging.INFO. These would be parameters of the according function. The statistics function would only allow the two strings logging.INFO and logging.DEBUG.

I would also rename persistencyUtil to persistenceUtil as this seems more natural to me.

What do you think?

**Comment by landauermax** [comment]
Sounds good. Renaming persistencyUtil is not related to this issue, please create another issue for that.

**Comment by dITySoftware** [comment]
implemented in PR #205.

**Comment by dITySoftware** [comment]
This issue should be moved into done after being accepted.
